/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEasyWallValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.easywall.easyWall.EasyWallPackage.eINSTANCE);
		return result;
	}
}
