/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage
 * @generated
 */
public interface EasyWallFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EasyWallFactory eINSTANCE = org.xtext.example.easywall.easyWall.impl.EasyWallFactoryImpl.init();

  /**
   * Returns a new object of class '<em>EF Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Program</em>'.
   * @generated
   */
  EFProgram createEFProgram();

  /**
   * Returns a new object of class '<em>EF Header</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Header</em>'.
   * @generated
   */
  EFHeader createEFHeader();

  /**
   * Returns a new object of class '<em>EF Imports</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Imports</em>'.
   * @generated
   */
  EFImports createEFImports();

  /**
   * Returns a new object of class '<em>EF Firewall</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Firewall</em>'.
   * @generated
   */
  EFFirewall createEFFirewall();

  /**
   * Returns a new object of class '<em>EF Default Policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Default Policy</em>'.
   * @generated
   */
  EFDefaultPolicy createEFDefaultPolicy();

  /**
   * Returns a new object of class '<em>EF Rule Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rule Reference</em>'.
   * @generated
   */
  EFRuleReference createEFRuleReference();

  /**
   * Returns a new object of class '<em>EF Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Member</em>'.
   * @generated
   */
  EFMember createEFMember();

  /**
   * Returns a new object of class '<em>EF Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Field</em>'.
   * @generated
   */
  EFField createEFField();

  /**
   * Returns a new object of class '<em>EF Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Variable Declaration</em>'.
   * @generated
   */
  EFVariableDeclaration createEFVariableDeclaration();

  /**
   * Returns a new object of class '<em>EF Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Method</em>'.
   * @generated
   */
  EFMethod createEFMethod();

  /**
   * Returns a new object of class '<em>EF Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Parameter</em>'.
   * @generated
   */
  EFParameter createEFParameter();

  /**
   * Returns a new object of class '<em>EF Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Block</em>'.
   * @generated
   */
  EFBlock createEFBlock();

  /**
   * Returns a new object of class '<em>EF Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Statement</em>'.
   * @generated
   */
  EFStatement createEFStatement();

  /**
   * Returns a new object of class '<em>EF Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Return</em>'.
   * @generated
   */
  EFReturn createEFReturn();

  /**
   * Returns a new object of class '<em>EF If Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF If Statement</em>'.
   * @generated
   */
  EFIfStatement createEFIfStatement();

  /**
   * Returns a new object of class '<em>EF Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Expression</em>'.
   * @generated
   */
  EFExpression createEFExpression();

  /**
   * Returns a new object of class '<em>EF Builtin Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Builtin Function</em>'.
   * @generated
   */
  EFBuiltinFunction createEFBuiltinFunction();

  /**
   * Returns a new object of class '<em>EF Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rule</em>'.
   * @generated
   */
  EFRule createEFRule();

  /**
   * Returns a new object of class '<em>EF Rule Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rule Class</em>'.
   * @generated
   */
  EFRuleClass createEFRuleClass();

  /**
   * Returns a new object of class '<em>EF Network Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Network Constant</em>'.
   * @generated
   */
  EFNetworkConstant createEFNetworkConstant();

  /**
   * Returns a new object of class '<em>EF Netport Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Netport Constant</em>'.
   * @generated
   */
  EFNetportConstant createEFNetportConstant();

  /**
   * Returns a new object of class '<em>EF Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Assignment</em>'.
   * @generated
   */
  EFAssignment createEFAssignment();

  /**
   * Returns a new object of class '<em>EF Or Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Or Expression</em>'.
   * @generated
   */
  EFOrExpression createEFOrExpression();

  /**
   * Returns a new object of class '<em>EF And Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF And Expression</em>'.
   * @generated
   */
  EFAndExpression createEFAndExpression();

  /**
   * Returns a new object of class '<em>EF Equal Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Equal Expression</em>'.
   * @generated
   */
  EFEqualExpression createEFEqualExpression();

  /**
   * Returns a new object of class '<em>EF Rel Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Rel Expression</em>'.
   * @generated
   */
  EFRelExpression createEFRelExpression();

  /**
   * Returns a new object of class '<em>EF Add Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Add Expression</em>'.
   * @generated
   */
  EFAddExpression createEFAddExpression();

  /**
   * Returns a new object of class '<em>EF Mult Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Mult Expression</em>'.
   * @generated
   */
  EFMultExpression createEFMultExpression();

  /**
   * Returns a new object of class '<em>EF Not Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Not Expression</em>'.
   * @generated
   */
  EFNotExpression createEFNotExpression();

  /**
   * Returns a new object of class '<em>EF Member Selection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Member Selection</em>'.
   * @generated
   */
  EFMemberSelection createEFMemberSelection();

  /**
   * Returns a new object of class '<em>EF String Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF String Constant</em>'.
   * @generated
   */
  EFStringConstant createEFStringConstant();

  /**
   * Returns a new object of class '<em>EF Int Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Int Constant</em>'.
   * @generated
   */
  EFIntConstant createEFIntConstant();

  /**
   * Returns a new object of class '<em>EF Bool Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Bool Constant</em>'.
   * @generated
   */
  EFBoolConstant createEFBoolConstant();

  /**
   * Returns a new object of class '<em>EF Direction Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Direction Constant</em>'.
   * @generated
   */
  EFDirectionConstant createEFDirectionConstant();

  /**
   * Returns a new object of class '<em>EF Network Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Network Protocol Constant</em>'.
   * @generated
   */
  EFNetworkProtocolConstant createEFNetworkProtocolConstant();

  /**
   * Returns a new object of class '<em>EF Transport Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Transport Protocol Constant</em>'.
   * @generated
   */
  EFTransportProtocolConstant createEFTransportProtocolConstant();

  /**
   * Returns a new object of class '<em>EF Application Protocol Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Application Protocol Constant</em>'.
   * @generated
   */
  EFApplicationProtocolConstant createEFApplicationProtocolConstant();

  /**
   * Returns a new object of class '<em>EFI Pv6 Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFI Pv6 Constant</em>'.
   * @generated
   */
  EFIPv6Constant createEFIPv6Constant();

  /**
   * Returns a new object of class '<em>EFI Pv4 Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFI Pv4 Constant</em>'.
   * @generated
   */
  EFIPv4Constant createEFIPv4Constant();

  /**
   * Returns a new object of class '<em>EF This</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF This</em>'.
   * @generated
   */
  EFThis createEFThis();

  /**
   * Returns a new object of class '<em>EF Super</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Super</em>'.
   * @generated
   */
  EFSuper createEFSuper();

  /**
   * Returns a new object of class '<em>EF New</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF New</em>'.
   * @generated
   */
  EFNew createEFNew();

  /**
   * Returns a new object of class '<em>EF Brackets Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Brackets Expression</em>'.
   * @generated
   */
  EFBracketsExpression createEFBracketsExpression();

  /**
   * Returns a new object of class '<em>EF Function Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Function Call</em>'.
   * @generated
   */
  EFFunctionCall createEFFunctionCall();

  /**
   * Returns a new object of class '<em>EF Symbol Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Symbol Ref</em>'.
   * @generated
   */
  EFSymbolRef createEFSymbolRef();

  /**
   * Returns a new object of class '<em>EF Allow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Allow</em>'.
   * @generated
   */
  EFAllow createEFAllow();

  /**
   * Returns a new object of class '<em>EF Drop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Drop</em>'.
   * @generated
   */
  EFDrop createEFDrop();

  /**
   * Returns a new object of class '<em>EF Reject</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Reject</em>'.
   * @generated
   */
  EFReject createEFReject();

  /**
   * Returns a new object of class '<em>EF Write Log</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Write Log</em>'.
   * @generated
   */
  EFWriteLog createEFWriteLog();

  /**
   * Returns a new object of class '<em>EF Write Log Level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Write Log Level</em>'.
   * @generated
   */
  EFWriteLogLevel createEFWriteLogLevel();

  /**
   * Returns a new object of class '<em>EF Get Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Get Time</em>'.
   * @generated
   */
  EFGetTime createEFGetTime();

  /**
   * Returns a new object of class '<em>EF Get Packet Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF Get Packet Field</em>'.
   * @generated
   */
  EFGetPacketField createEFGetPacketField();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EasyWallPackage getEasyWallPackage();

} //EasyWallFactory
