/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Allow</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFAllow()
 * @model
 * @generated
 */
public interface EFAllow extends EFBuiltinFunction
{
} // EFAllow
