/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFAssignment#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFAssignment#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFAssignment()
 * @model
 * @generated
 */
public interface EFAssignment extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFAssignment_Left()
   * @model containment="true"
   * @generated
   */
  EFExpression getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFAssignment#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EFExpression value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFAssignment_Right()
   * @model containment="true"
   * @generated
   */
  EFExpression getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFAssignment#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(EFExpression value);

} // EFAssignment
