/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Brackets Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFBracketsExpression#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFBracketsExpression()
 * @model
 * @generated
 */
public interface EFBracketsExpression extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFBracketsExpression_Expression()
   * @model containment="true"
   * @generated
   */
  EFExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFBracketsExpression#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(EFExpression value);

} // EFBracketsExpression
