/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Firewall</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFirewall#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFirewall#getDefaultPolicy <em>Default Policy</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFirewall#getMembers <em>Members</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFirewall#getRuleRefs <em>Rule Refs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFirewall()
 * @model
 * @generated
 */
public interface EFFirewall extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFirewall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFFirewall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Default Policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Policy</em>' containment reference.
   * @see #setDefaultPolicy(EFDefaultPolicy)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFirewall_DefaultPolicy()
   * @model containment="true"
   * @generated
   */
  EFDefaultPolicy getDefaultPolicy();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFFirewall#getDefaultPolicy <em>Default Policy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Policy</em>' containment reference.
   * @see #getDefaultPolicy()
   * @generated
   */
  void setDefaultPolicy(EFDefaultPolicy value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFMember}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFirewall_Members()
   * @model containment="true"
   * @generated
   */
  EList<EFMember> getMembers();

  /**
   * Returns the value of the '<em><b>Rule Refs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFRuleReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Refs</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFirewall_RuleRefs()
   * @model containment="true"
   * @generated
   */
  EList<EFRuleReference> getRuleRefs();

} // EFFirewall
