/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFunctionCall#getFunctionName <em>Function Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFFunctionCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFunctionCall()
 * @model
 * @generated
 */
public interface EFFunctionCall extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Function Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Name</em>' attribute.
   * @see #setFunctionName(String)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFunctionCall_FunctionName()
   * @model
   * @generated
   */
  String getFunctionName();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFFunctionCall#getFunctionName <em>Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Name</em>' attribute.
   * @see #getFunctionName()
   * @generated
   */
  void setFunctionName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFFunctionCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<EFExpression> getArgs();

} // EFFunctionCall
