/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFIfStatement#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFIfStatement#getThenBlock <em>Then Block</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFIfStatement#getElseBlock <em>Else Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFIfStatement()
 * @model
 * @generated
 */
public interface EFIfStatement extends EFStatement
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFIfStatement_Expression()
   * @model containment="true"
   * @generated
   */
  EFExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFIfStatement#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(EFExpression value);

  /**
   * Returns the value of the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Block</em>' containment reference.
   * @see #setThenBlock(EFBlock)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFIfStatement_ThenBlock()
   * @model containment="true"
   * @generated
   */
  EFBlock getThenBlock();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFIfStatement#getThenBlock <em>Then Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Block</em>' containment reference.
   * @see #getThenBlock()
   * @generated
   */
  void setThenBlock(EFBlock value);

  /**
   * Returns the value of the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Block</em>' containment reference.
   * @see #setElseBlock(EFBlock)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFIfStatement_ElseBlock()
   * @model containment="true"
   * @generated
   */
  EFBlock getElseBlock();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFIfStatement#getElseBlock <em>Else Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Block</em>' containment reference.
   * @see #getElseBlock()
   * @generated
   */
  void setElseBlock(EFBlock value);

} // EFIfStatement
