/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMethod#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMethod#getNativetype <em>Nativetype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMethod#getVoid <em>Void</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMethod#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMethod()
 * @model
 * @generated
 */
public interface EFMethod extends EFMember
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMethod_Params()
   * @model containment="true"
   * @generated
   */
  EList<EFParameter> getParams();

  /**
   * Returns the value of the '<em><b>Nativetype</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.easywall.easyWall.EFType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nativetype</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFType
   * @see #setNativetype(EFType)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMethod_Nativetype()
   * @model
   * @generated
   */
  EFType getNativetype();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFMethod#getNativetype <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nativetype</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.EFType
   * @see #getNativetype()
   * @generated
   */
  void setNativetype(EFType value);

  /**
   * Returns the value of the '<em><b>Void</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Void</em>' attribute.
   * @see #setVoid(String)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMethod_Void()
   * @model
   * @generated
   */
  String getVoid();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFMethod#getVoid <em>Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Void</em>' attribute.
   * @see #getVoid()
   * @generated
   */
  void setVoid(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(EFBlock)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMethod_Body()
   * @model containment="true"
   * @generated
   */
  EFBlock getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFMethod#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(EFBlock value);

} // EFMethod
