/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Member Selection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMemberSelection#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMemberSelection#getMember <em>Member</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFMemberSelection#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMemberSelection()
 * @model
 * @generated
 */
public interface EFMemberSelection extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' containment reference.
   * @see #setReceiver(EFExpression)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMemberSelection_Receiver()
   * @model containment="true"
   * @generated
   */
  EFExpression getReceiver();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFMemberSelection#getReceiver <em>Receiver</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' containment reference.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(EFExpression value);

  /**
   * Returns the value of the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' reference.
   * @see #setMember(EFMember)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMemberSelection_Member()
   * @model
   * @generated
   */
  EFMember getMember();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFMemberSelection#getMember <em>Member</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member</em>' reference.
   * @see #getMember()
   * @generated
   */
  void setMember(EFMember value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.easywall.easyWall.EFExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFMemberSelection_Args()
   * @model containment="true"
   * @generated
   */
  EList<EFExpression> getArgs();

} // EFMemberSelection
