/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>EF Network Native Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFNetworkNativeType()
 * @model
 * @generated
 */
public enum EFNetworkNativeType implements Enumerator
{
  /**
   * The '<em><b>NETWORK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETWORK_VALUE
   * @generated
   * @ordered
   */
  NETWORK(0, "NETWORK", "network"),

  /**
   * The '<em><b>IPv4</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IPV4_VALUE
   * @generated
   * @ordered
   */
  IPV4(1, "IPv4", "netip"),

  /**
   * The '<em><b>IPv6</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IPV6_VALUE
   * @generated
   * @ordered
   */
  IPV6(2, "IPv6", "netipv6"),

  /**
   * The '<em><b>PORT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PORT_VALUE
   * @generated
   * @ordered
   */
  PORT(3, "PORT", "netport"),

  /**
   * The '<em><b>PROTOCOL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROTOCOL_VALUE
   * @generated
   * @ordered
   */
  PROTOCOL(4, "PROTOCOL", "protocol"),

  /**
   * The '<em><b>DIRECTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIRECTION_VALUE
   * @generated
   * @ordered
   */
  DIRECTION(5, "DIRECTION", "direction"),

  /**
   * The '<em><b>NETMASK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETMASK_VALUE
   * @generated
   * @ordered
   */
  NETMASK(6, "NETMASK", "netmask");

  /**
   * The '<em><b>NETWORK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETWORK
   * @model literal="network"
   * @generated
   * @ordered
   */
  public static final int NETWORK_VALUE = 0;

  /**
   * The '<em><b>IPv4</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IPV4
   * @model name="IPv4" literal="netip"
   * @generated
   * @ordered
   */
  public static final int IPV4_VALUE = 1;

  /**
   * The '<em><b>IPv6</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IPV6
   * @model name="IPv6" literal="netipv6"
   * @generated
   * @ordered
   */
  public static final int IPV6_VALUE = 2;

  /**
   * The '<em><b>PORT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PORT
   * @model literal="netport"
   * @generated
   * @ordered
   */
  public static final int PORT_VALUE = 3;

  /**
   * The '<em><b>PROTOCOL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROTOCOL
   * @model literal="protocol"
   * @generated
   * @ordered
   */
  public static final int PROTOCOL_VALUE = 4;

  /**
   * The '<em><b>DIRECTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIRECTION
   * @model literal="direction"
   * @generated
   * @ordered
   */
  public static final int DIRECTION_VALUE = 5;

  /**
   * The '<em><b>NETMASK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETMASK
   * @model literal="netmask"
   * @generated
   * @ordered
   */
  public static final int NETMASK_VALUE = 6;

  /**
   * An array of all the '<em><b>EF Network Native Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final EFNetworkNativeType[] VALUES_ARRAY =
    new EFNetworkNativeType[]
    {
      NETWORK,
      IPV4,
      IPV6,
      PORT,
      PROTOCOL,
      DIRECTION,
      NETMASK,
    };

  /**
   * A public read-only list of all the '<em><b>EF Network Native Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<EFNetworkNativeType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>EF Network Native Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EFNetworkNativeType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      EFNetworkNativeType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>EF Network Native Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EFNetworkNativeType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      EFNetworkNativeType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>EF Network Native Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static EFNetworkNativeType get(int value)
  {
    switch (value)
    {
      case NETWORK_VALUE: return NETWORK;
      case IPV4_VALUE: return IPV4;
      case IPV6_VALUE: return IPV6;
      case PORT_VALUE: return PORT;
      case PROTOCOL_VALUE: return PROTOCOL;
      case DIRECTION_VALUE: return DIRECTION;
      case NETMASK_VALUE: return NETMASK;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EFNetworkNativeType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //EFNetworkNativeType
