/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFStatement()
 * @model
 * @generated
 */
public interface EFStatement extends EObject
{
} // EFStatement
