/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF Transport Protocol Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.EFTransportProtocolConstant#getProtocol <em>Protocol</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTransportProtocolConstant()
 * @model
 * @generated
 */
public interface EFTransportProtocolConstant extends EFExpression
{
  /**
   * Returns the value of the '<em><b>Protocol</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL
   * @see #setProtocol(TRANSPORTLAYERPROTOCOL)
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#getEFTransportProtocolConstant_Protocol()
   * @model
   * @generated
   */
  TRANSPORTLAYERPROTOCOL getProtocol();

  /**
   * Sets the value of the '{@link org.xtext.example.easywall.easyWall.EFTransportProtocolConstant#getProtocol <em>Protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' attribute.
   * @see org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(TRANSPORTLAYERPROTOCOL value);

} // EFTransportProtocolConstant
