/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.xtext.example.easywall.easyWall.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.easywall.easyWall.EasyWallPackage
 * @generated
 */
public class EasyWallAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static EasyWallPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EasyWallAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = EasyWallPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EasyWallSwitch<Adapter> modelSwitch =
    new EasyWallSwitch<Adapter>()
    {
      @Override
      public Adapter caseEFProgram(EFProgram object)
      {
        return createEFProgramAdapter();
      }
      @Override
      public Adapter caseEFHeader(EFHeader object)
      {
        return createEFHeaderAdapter();
      }
      @Override
      public Adapter caseEFImports(EFImports object)
      {
        return createEFImportsAdapter();
      }
      @Override
      public Adapter caseEFFirewall(EFFirewall object)
      {
        return createEFFirewallAdapter();
      }
      @Override
      public Adapter caseEFDefaultPolicy(EFDefaultPolicy object)
      {
        return createEFDefaultPolicyAdapter();
      }
      @Override
      public Adapter caseEFRuleReference(EFRuleReference object)
      {
        return createEFRuleReferenceAdapter();
      }
      @Override
      public Adapter caseEFMember(EFMember object)
      {
        return createEFMemberAdapter();
      }
      @Override
      public Adapter caseEFField(EFField object)
      {
        return createEFFieldAdapter();
      }
      @Override
      public Adapter caseEFVariableDeclaration(EFVariableDeclaration object)
      {
        return createEFVariableDeclarationAdapter();
      }
      @Override
      public Adapter caseEFMethod(EFMethod object)
      {
        return createEFMethodAdapter();
      }
      @Override
      public Adapter caseEFParameter(EFParameter object)
      {
        return createEFParameterAdapter();
      }
      @Override
      public Adapter caseEFBlock(EFBlock object)
      {
        return createEFBlockAdapter();
      }
      @Override
      public Adapter caseEFStatement(EFStatement object)
      {
        return createEFStatementAdapter();
      }
      @Override
      public Adapter caseEFReturn(EFReturn object)
      {
        return createEFReturnAdapter();
      }
      @Override
      public Adapter caseEFIfStatement(EFIfStatement object)
      {
        return createEFIfStatementAdapter();
      }
      @Override
      public Adapter caseEFExpression(EFExpression object)
      {
        return createEFExpressionAdapter();
      }
      @Override
      public Adapter caseEFBuiltinFunction(EFBuiltinFunction object)
      {
        return createEFBuiltinFunctionAdapter();
      }
      @Override
      public Adapter caseEFRule(EFRule object)
      {
        return createEFRuleAdapter();
      }
      @Override
      public Adapter caseEFRuleClass(EFRuleClass object)
      {
        return createEFRuleClassAdapter();
      }
      @Override
      public Adapter caseEFNetworkConstant(EFNetworkConstant object)
      {
        return createEFNetworkConstantAdapter();
      }
      @Override
      public Adapter caseEFNetportConstant(EFNetportConstant object)
      {
        return createEFNetportConstantAdapter();
      }
      @Override
      public Adapter caseEFAssignment(EFAssignment object)
      {
        return createEFAssignmentAdapter();
      }
      @Override
      public Adapter caseEFOrExpression(EFOrExpression object)
      {
        return createEFOrExpressionAdapter();
      }
      @Override
      public Adapter caseEFAndExpression(EFAndExpression object)
      {
        return createEFAndExpressionAdapter();
      }
      @Override
      public Adapter caseEFEqualExpression(EFEqualExpression object)
      {
        return createEFEqualExpressionAdapter();
      }
      @Override
      public Adapter caseEFRelExpression(EFRelExpression object)
      {
        return createEFRelExpressionAdapter();
      }
      @Override
      public Adapter caseEFAddExpression(EFAddExpression object)
      {
        return createEFAddExpressionAdapter();
      }
      @Override
      public Adapter caseEFMultExpression(EFMultExpression object)
      {
        return createEFMultExpressionAdapter();
      }
      @Override
      public Adapter caseEFNotExpression(EFNotExpression object)
      {
        return createEFNotExpressionAdapter();
      }
      @Override
      public Adapter caseEFMemberSelection(EFMemberSelection object)
      {
        return createEFMemberSelectionAdapter();
      }
      @Override
      public Adapter caseEFStringConstant(EFStringConstant object)
      {
        return createEFStringConstantAdapter();
      }
      @Override
      public Adapter caseEFIntConstant(EFIntConstant object)
      {
        return createEFIntConstantAdapter();
      }
      @Override
      public Adapter caseEFBoolConstant(EFBoolConstant object)
      {
        return createEFBoolConstantAdapter();
      }
      @Override
      public Adapter caseEFDirectionConstant(EFDirectionConstant object)
      {
        return createEFDirectionConstantAdapter();
      }
      @Override
      public Adapter caseEFNetworkProtocolConstant(EFNetworkProtocolConstant object)
      {
        return createEFNetworkProtocolConstantAdapter();
      }
      @Override
      public Adapter caseEFTransportProtocolConstant(EFTransportProtocolConstant object)
      {
        return createEFTransportProtocolConstantAdapter();
      }
      @Override
      public Adapter caseEFApplicationProtocolConstant(EFApplicationProtocolConstant object)
      {
        return createEFApplicationProtocolConstantAdapter();
      }
      @Override
      public Adapter caseEFIPv6Constant(EFIPv6Constant object)
      {
        return createEFIPv6ConstantAdapter();
      }
      @Override
      public Adapter caseEFIPv4Constant(EFIPv4Constant object)
      {
        return createEFIPv4ConstantAdapter();
      }
      @Override
      public Adapter caseEFThis(EFThis object)
      {
        return createEFThisAdapter();
      }
      @Override
      public Adapter caseEFSuper(EFSuper object)
      {
        return createEFSuperAdapter();
      }
      @Override
      public Adapter caseEFNew(EFNew object)
      {
        return createEFNewAdapter();
      }
      @Override
      public Adapter caseEFBracketsExpression(EFBracketsExpression object)
      {
        return createEFBracketsExpressionAdapter();
      }
      @Override
      public Adapter caseEFFunctionCall(EFFunctionCall object)
      {
        return createEFFunctionCallAdapter();
      }
      @Override
      public Adapter caseEFSymbolRef(EFSymbolRef object)
      {
        return createEFSymbolRefAdapter();
      }
      @Override
      public Adapter caseEFAllow(EFAllow object)
      {
        return createEFAllowAdapter();
      }
      @Override
      public Adapter caseEFDrop(EFDrop object)
      {
        return createEFDropAdapter();
      }
      @Override
      public Adapter caseEFReject(EFReject object)
      {
        return createEFRejectAdapter();
      }
      @Override
      public Adapter caseEFWriteLog(EFWriteLog object)
      {
        return createEFWriteLogAdapter();
      }
      @Override
      public Adapter caseEFWriteLogLevel(EFWriteLogLevel object)
      {
        return createEFWriteLogLevelAdapter();
      }
      @Override
      public Adapter caseEFGetTime(EFGetTime object)
      {
        return createEFGetTimeAdapter();
      }
      @Override
      public Adapter caseEFGetPacketField(EFGetPacketField object)
      {
        return createEFGetPacketFieldAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFProgram <em>EF Program</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFProgram
   * @generated
   */
  public Adapter createEFProgramAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFHeader <em>EF Header</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFHeader
   * @generated
   */
  public Adapter createEFHeaderAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFImports <em>EF Imports</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFImports
   * @generated
   */
  public Adapter createEFImportsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFFirewall <em>EF Firewall</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFFirewall
   * @generated
   */
  public Adapter createEFFirewallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFDefaultPolicy <em>EF Default Policy</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFDefaultPolicy
   * @generated
   */
  public Adapter createEFDefaultPolicyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFRuleReference <em>EF Rule Reference</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFRuleReference
   * @generated
   */
  public Adapter createEFRuleReferenceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFMember <em>EF Member</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFMember
   * @generated
   */
  public Adapter createEFMemberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFField <em>EF Field</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFField
   * @generated
   */
  public Adapter createEFFieldAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFVariableDeclaration <em>EF Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFVariableDeclaration
   * @generated
   */
  public Adapter createEFVariableDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFMethod <em>EF Method</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFMethod
   * @generated
   */
  public Adapter createEFMethodAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFParameter <em>EF Parameter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFParameter
   * @generated
   */
  public Adapter createEFParameterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFBlock <em>EF Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFBlock
   * @generated
   */
  public Adapter createEFBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFStatement <em>EF Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFStatement
   * @generated
   */
  public Adapter createEFStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFReturn <em>EF Return</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFReturn
   * @generated
   */
  public Adapter createEFReturnAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFIfStatement <em>EF If Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFIfStatement
   * @generated
   */
  public Adapter createEFIfStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFExpression <em>EF Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFExpression
   * @generated
   */
  public Adapter createEFExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFBuiltinFunction <em>EF Builtin Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFBuiltinFunction
   * @generated
   */
  public Adapter createEFBuiltinFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFRule <em>EF Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFRule
   * @generated
   */
  public Adapter createEFRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFRuleClass <em>EF Rule Class</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFRuleClass
   * @generated
   */
  public Adapter createEFRuleClassAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFNetworkConstant <em>EF Network Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFNetworkConstant
   * @generated
   */
  public Adapter createEFNetworkConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFNetportConstant <em>EF Netport Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFNetportConstant
   * @generated
   */
  public Adapter createEFNetportConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFAssignment <em>EF Assignment</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFAssignment
   * @generated
   */
  public Adapter createEFAssignmentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFOrExpression <em>EF Or Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFOrExpression
   * @generated
   */
  public Adapter createEFOrExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFAndExpression <em>EF And Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFAndExpression
   * @generated
   */
  public Adapter createEFAndExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFEqualExpression <em>EF Equal Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFEqualExpression
   * @generated
   */
  public Adapter createEFEqualExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFRelExpression <em>EF Rel Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFRelExpression
   * @generated
   */
  public Adapter createEFRelExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFAddExpression <em>EF Add Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFAddExpression
   * @generated
   */
  public Adapter createEFAddExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFMultExpression <em>EF Mult Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFMultExpression
   * @generated
   */
  public Adapter createEFMultExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFNotExpression <em>EF Not Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFNotExpression
   * @generated
   */
  public Adapter createEFNotExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFMemberSelection <em>EF Member Selection</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFMemberSelection
   * @generated
   */
  public Adapter createEFMemberSelectionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFStringConstant <em>EF String Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFStringConstant
   * @generated
   */
  public Adapter createEFStringConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFIntConstant <em>EF Int Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFIntConstant
   * @generated
   */
  public Adapter createEFIntConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFBoolConstant <em>EF Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFBoolConstant
   * @generated
   */
  public Adapter createEFBoolConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFDirectionConstant <em>EF Direction Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFDirectionConstant
   * @generated
   */
  public Adapter createEFDirectionConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFNetworkProtocolConstant <em>EF Network Protocol Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFNetworkProtocolConstant
   * @generated
   */
  public Adapter createEFNetworkProtocolConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFTransportProtocolConstant <em>EF Transport Protocol Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFTransportProtocolConstant
   * @generated
   */
  public Adapter createEFTransportProtocolConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFApplicationProtocolConstant <em>EF Application Protocol Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFApplicationProtocolConstant
   * @generated
   */
  public Adapter createEFApplicationProtocolConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFIPv6Constant <em>EFI Pv6 Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFIPv6Constant
   * @generated
   */
  public Adapter createEFIPv6ConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFIPv4Constant <em>EFI Pv4 Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFIPv4Constant
   * @generated
   */
  public Adapter createEFIPv4ConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFThis <em>EF This</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFThis
   * @generated
   */
  public Adapter createEFThisAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFSuper <em>EF Super</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFSuper
   * @generated
   */
  public Adapter createEFSuperAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFNew <em>EF New</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFNew
   * @generated
   */
  public Adapter createEFNewAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFBracketsExpression <em>EF Brackets Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFBracketsExpression
   * @generated
   */
  public Adapter createEFBracketsExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFFunctionCall <em>EF Function Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFFunctionCall
   * @generated
   */
  public Adapter createEFFunctionCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFSymbolRef <em>EF Symbol Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFSymbolRef
   * @generated
   */
  public Adapter createEFSymbolRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFAllow <em>EF Allow</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFAllow
   * @generated
   */
  public Adapter createEFAllowAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFDrop <em>EF Drop</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFDrop
   * @generated
   */
  public Adapter createEFDropAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFReject <em>EF Reject</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFReject
   * @generated
   */
  public Adapter createEFRejectAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFWriteLog <em>EF Write Log</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFWriteLog
   * @generated
   */
  public Adapter createEFWriteLogAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFWriteLogLevel <em>EF Write Log Level</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFWriteLogLevel
   * @generated
   */
  public Adapter createEFWriteLogLevelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFGetTime <em>EF Get Time</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFGetTime
   * @generated
   */
  public Adapter createEFGetTimeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.easywall.easyWall.EFGetPacketField <em>EF Get Packet Field</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.easywall.easyWall.EFGetPacketField
   * @generated
   */
  public Adapter createEFGetPacketFieldAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //EasyWallAdapterFactory
