/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.easywall.services.EasyWallGrammarAccess;

@SuppressWarnings("all")
public class EasyWallSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EasyWallGrammarAccess grammarAccess;
	protected AbstractElementAlias match_EFField_SetKeyword_0_0_or_VarKeyword_0_1;
	protected AbstractElementAlias match_EFMemberSelection___LeftParenthesisKeyword_1_3_0_RightParenthesisKeyword_1_3_2__q;
	protected AbstractElementAlias match_EFVariableDeclaration_SetKeyword_0_0_or_VarKeyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EasyWallGrammarAccess) access;
		match_EFField_SetKeyword_0_0_or_VarKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getEFFieldAccess().getSetKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getEFFieldAccess().getVarKeyword_0_1()));
		match_EFMemberSelection___LeftParenthesisKeyword_1_3_0_RightParenthesisKeyword_1_3_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEFMemberSelectionAccess().getLeftParenthesisKeyword_1_3_0()), new TokenAlias(false, false, grammarAccess.getEFMemberSelectionAccess().getRightParenthesisKeyword_1_3_2()));
		match_EFVariableDeclaration_SetKeyword_0_0_or_VarKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getEFVariableDeclarationAccess().getSetKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getEFVariableDeclarationAccess().getVarKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getEFAddOperatorsRule())
			return getEFAddOperatorsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFAndRule())
			return getEFAndToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFEqualOperatorsRule())
			return getEFEqualOperatorsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFMultOperatorsRule())
			return getEFMultOperatorsToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFNotRule())
			return getEFNotToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFOrRule())
			return getEFOrToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEFRelOperatorsRule())
			return getEFRelOperatorsToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * EFAddOperators: '+' | '-';
	 */
	protected String getEFAddOperatorsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "+";
	}
	
	/**
	 * EFAnd: '&&' | 'and';
	 */
	protected String getEFAndToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "&&";
	}
	
	/**
	 * EFEqualOperators: '==' | '!=' | 'isequalto';
	 */
	protected String getEFEqualOperatorsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "==";
	}
	
	/**
	 * EFMultOperators: '*' | 'div' | '%';
	 */
	protected String getEFMultOperatorsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "*";
	}
	
	/**
	 * EFNot: '!' | 'not';
	 */
	protected String getEFNotToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "!";
	}
	
	/**
	 * EFOr: '||' | 'or';
	 */
	protected String getEFOrToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "||";
	}
	
	/**
	 * EFRelOperators: '>=' | '<=' | '>' | '<';
	 */
	protected String getEFRelOperatorsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ">=";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_EFField_SetKeyword_0_0_or_VarKeyword_0_1.equals(syntax))
				emit_EFField_SetKeyword_0_0_or_VarKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EFMemberSelection___LeftParenthesisKeyword_1_3_0_RightParenthesisKeyword_1_3_2__q.equals(syntax))
				emit_EFMemberSelection___LeftParenthesisKeyword_1_3_0_RightParenthesisKeyword_1_3_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EFVariableDeclaration_SetKeyword_0_0_or_VarKeyword_0_1.equals(syntax))
				emit_EFVariableDeclaration_SetKeyword_0_0_or_VarKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'set' | 'var'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 
	 * </pre>
	 */
	protected void emit_EFField_SetKeyword_0_0_or_VarKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     member=[EFMember|ID] (ambiguity) ';' (rule end)
	 *     member=[EFMember|ID] (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_EFMemberSelection___LeftParenthesisKeyword_1_3_0_RightParenthesisKeyword_1_3_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'set' | 'var'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 
	 * </pre>
	 */
	protected void emit_EFVariableDeclaration_SetKeyword_0_0_or_VarKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
