/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEasyWallScopeProvider extends DelegatingScopeProvider {
}
