/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.easywall.easyWall.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EasyWallFactoryImpl extends EFactoryImpl implements EasyWallFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static EasyWallFactory init()
  {
    try
    {
      EasyWallFactory theEasyWallFactory = (EasyWallFactory)EPackage.Registry.INSTANCE.getEFactory(EasyWallPackage.eNS_URI);
      if (theEasyWallFactory != null)
      {
        return theEasyWallFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new EasyWallFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EasyWallFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case EasyWallPackage.EF_PROGRAM: return createEFProgram();
      case EasyWallPackage.EF_HEADER: return createEFHeader();
      case EasyWallPackage.EF_IMPORTS: return createEFImports();
      case EasyWallPackage.EF_FIREWALL: return createEFFirewall();
      case EasyWallPackage.EF_DEFAULT_POLICY: return createEFDefaultPolicy();
      case EasyWallPackage.EF_RULE_REFERENCE: return createEFRuleReference();
      case EasyWallPackage.EF_MEMBER: return createEFMember();
      case EasyWallPackage.EF_FIELD: return createEFField();
      case EasyWallPackage.EF_VARIABLE_DECLARATION: return createEFVariableDeclaration();
      case EasyWallPackage.EF_METHOD: return createEFMethod();
      case EasyWallPackage.EF_PARAMETER: return createEFParameter();
      case EasyWallPackage.EF_BLOCK: return createEFBlock();
      case EasyWallPackage.EF_STATEMENT: return createEFStatement();
      case EasyWallPackage.EF_RETURN: return createEFReturn();
      case EasyWallPackage.EF_IF_STATEMENT: return createEFIfStatement();
      case EasyWallPackage.EF_EXPRESSION: return createEFExpression();
      case EasyWallPackage.EF_BUILTIN_FUNCTION: return createEFBuiltinFunction();
      case EasyWallPackage.EF_RULE: return createEFRule();
      case EasyWallPackage.EF_RULE_CLASS: return createEFRuleClass();
      case EasyWallPackage.EF_NETWORK_CONSTANT: return createEFNetworkConstant();
      case EasyWallPackage.EF_NETMASK_CONSTANT: return createEFNetmaskConstant();
      case EasyWallPackage.EF_NETPORT_CONSTANT: return createEFNetportConstant();
      case EasyWallPackage.EF_ASSIGNMENT: return createEFAssignment();
      case EasyWallPackage.EF_OR_EXPRESSION: return createEFOrExpression();
      case EasyWallPackage.EF_AND_EXPRESSION: return createEFAndExpression();
      case EasyWallPackage.EF_EQUAL_EXPRESSION: return createEFEqualExpression();
      case EasyWallPackage.EF_REL_EXPRESSION: return createEFRelExpression();
      case EasyWallPackage.EF_ADD_EXPRESSION: return createEFAddExpression();
      case EasyWallPackage.EF_MULT_EXPRESSION: return createEFMultExpression();
      case EasyWallPackage.EF_NOT_EXPRESSION: return createEFNotExpression();
      case EasyWallPackage.EF_MEMBER_SELECTION: return createEFMemberSelection();
      case EasyWallPackage.EF_STRING_CONSTANT: return createEFStringConstant();
      case EasyWallPackage.EF_INT_CONSTANT: return createEFIntConstant();
      case EasyWallPackage.EF_BOOL_CONSTANT: return createEFBoolConstant();
      case EasyWallPackage.EF_DIRECTION_CONSTANT: return createEFDirectionConstant();
      case EasyWallPackage.EF_NETWORK_PROTOCOL_CONSTANT: return createEFNetworkProtocolConstant();
      case EasyWallPackage.EF_TRANSPORT_PROTOCOL_CONSTANT: return createEFTransportProtocolConstant();
      case EasyWallPackage.EF_APPLICATION_PROTOCOL_CONSTANT: return createEFApplicationProtocolConstant();
      case EasyWallPackage.EFI_PV6_CONSTANT: return createEFIPv6Constant();
      case EasyWallPackage.EFI_PV4_CONSTANT: return createEFIPv4Constant();
      case EasyWallPackage.EF_THIS: return createEFThis();
      case EasyWallPackage.EF_SUPER: return createEFSuper();
      case EasyWallPackage.EF_NEW: return createEFNew();
      case EasyWallPackage.EF_BRACKETS_EXPRESSION: return createEFBracketsExpression();
      case EasyWallPackage.EF_FUNCTION_CALL: return createEFFunctionCall();
      case EasyWallPackage.EF_SYMBOL_REF: return createEFSymbolRef();
      case EasyWallPackage.EF_ALLOW: return createEFAllow();
      case EasyWallPackage.EF_DROP: return createEFDrop();
      case EasyWallPackage.EF_REJECT: return createEFReject();
      case EasyWallPackage.EF_WRITE_LOG: return createEFWriteLog();
      case EasyWallPackage.EF_WRITE_LOG_LEVEL: return createEFWriteLogLevel();
      case EasyWallPackage.EF_GET_TIME: return createEFGetTime();
      case EasyWallPackage.EF_GET_PACKET_FIELD: return createEFGetPacketField();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case EasyWallPackage.EF_DEFAULT_ACTION:
        return createEFDefaultActionFromString(eDataType, initialValue);
      case EasyWallPackage.EF_NETWORK_NATIVE_TYPE:
        return createEFNetworkNativeTypeFromString(eDataType, initialValue);
      case EasyWallPackage.EF_PRIMITIVE_TYPE:
        return createEFPrimitiveTypeFromString(eDataType, initialValue);
      case EasyWallPackage.EF_DIRECTION_NATIVE_TYPE:
        return createEFDirectionNativeTypeFromString(eDataType, initialValue);
      case EasyWallPackage.EF_LOG_LEVEL:
        return createEFLogLevelFromString(eDataType, initialValue);
      case EasyWallPackage.EF_RULES_TYPES:
        return createEFRulesTypesFromString(eDataType, initialValue);
      case EasyWallPackage.NETWORKLAYERPROTOCOL:
        return createNETWORKLAYERPROTOCOLFromString(eDataType, initialValue);
      case EasyWallPackage.TRANSPORTLAYERPROTOCOL:
        return createTRANSPORTLAYERPROTOCOLFromString(eDataType, initialValue);
      case EasyWallPackage.APPLICATIONLAYERPROTOCOL:
        return createAPPLICATIONLAYERPROTOCOLFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case EasyWallPackage.EF_DEFAULT_ACTION:
        return convertEFDefaultActionToString(eDataType, instanceValue);
      case EasyWallPackage.EF_NETWORK_NATIVE_TYPE:
        return convertEFNetworkNativeTypeToString(eDataType, instanceValue);
      case EasyWallPackage.EF_PRIMITIVE_TYPE:
        return convertEFPrimitiveTypeToString(eDataType, instanceValue);
      case EasyWallPackage.EF_DIRECTION_NATIVE_TYPE:
        return convertEFDirectionNativeTypeToString(eDataType, instanceValue);
      case EasyWallPackage.EF_LOG_LEVEL:
        return convertEFLogLevelToString(eDataType, instanceValue);
      case EasyWallPackage.EF_RULES_TYPES:
        return convertEFRulesTypesToString(eDataType, instanceValue);
      case EasyWallPackage.NETWORKLAYERPROTOCOL:
        return convertNETWORKLAYERPROTOCOLToString(eDataType, instanceValue);
      case EasyWallPackage.TRANSPORTLAYERPROTOCOL:
        return convertTRANSPORTLAYERPROTOCOLToString(eDataType, instanceValue);
      case EasyWallPackage.APPLICATIONLAYERPROTOCOL:
        return convertAPPLICATIONLAYERPROTOCOLToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFProgram createEFProgram()
  {
    EFProgramImpl efProgram = new EFProgramImpl();
    return efProgram;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFHeader createEFHeader()
  {
    EFHeaderImpl efHeader = new EFHeaderImpl();
    return efHeader;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFImports createEFImports()
  {
    EFImportsImpl efImports = new EFImportsImpl();
    return efImports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFFirewall createEFFirewall()
  {
    EFFirewallImpl efFirewall = new EFFirewallImpl();
    return efFirewall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFDefaultPolicy createEFDefaultPolicy()
  {
    EFDefaultPolicyImpl efDefaultPolicy = new EFDefaultPolicyImpl();
    return efDefaultPolicy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRuleReference createEFRuleReference()
  {
    EFRuleReferenceImpl efRuleReference = new EFRuleReferenceImpl();
    return efRuleReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFMember createEFMember()
  {
    EFMemberImpl efMember = new EFMemberImpl();
    return efMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFField createEFField()
  {
    EFFieldImpl efField = new EFFieldImpl();
    return efField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFVariableDeclaration createEFVariableDeclaration()
  {
    EFVariableDeclarationImpl efVariableDeclaration = new EFVariableDeclarationImpl();
    return efVariableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFMethod createEFMethod()
  {
    EFMethodImpl efMethod = new EFMethodImpl();
    return efMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFParameter createEFParameter()
  {
    EFParameterImpl efParameter = new EFParameterImpl();
    return efParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFBlock createEFBlock()
  {
    EFBlockImpl efBlock = new EFBlockImpl();
    return efBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFStatement createEFStatement()
  {
    EFStatementImpl efStatement = new EFStatementImpl();
    return efStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFReturn createEFReturn()
  {
    EFReturnImpl efReturn = new EFReturnImpl();
    return efReturn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFIfStatement createEFIfStatement()
  {
    EFIfStatementImpl efIfStatement = new EFIfStatementImpl();
    return efIfStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFExpression createEFExpression()
  {
    EFExpressionImpl efExpression = new EFExpressionImpl();
    return efExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFBuiltinFunction createEFBuiltinFunction()
  {
    EFBuiltinFunctionImpl efBuiltinFunction = new EFBuiltinFunctionImpl();
    return efBuiltinFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRule createEFRule()
  {
    EFRuleImpl efRule = new EFRuleImpl();
    return efRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRuleClass createEFRuleClass()
  {
    EFRuleClassImpl efRuleClass = new EFRuleClassImpl();
    return efRuleClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetworkConstant createEFNetworkConstant()
  {
    EFNetworkConstantImpl efNetworkConstant = new EFNetworkConstantImpl();
    return efNetworkConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetmaskConstant createEFNetmaskConstant()
  {
    EFNetmaskConstantImpl efNetmaskConstant = new EFNetmaskConstantImpl();
    return efNetmaskConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetportConstant createEFNetportConstant()
  {
    EFNetportConstantImpl efNetportConstant = new EFNetportConstantImpl();
    return efNetportConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFAssignment createEFAssignment()
  {
    EFAssignmentImpl efAssignment = new EFAssignmentImpl();
    return efAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFOrExpression createEFOrExpression()
  {
    EFOrExpressionImpl efOrExpression = new EFOrExpressionImpl();
    return efOrExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFAndExpression createEFAndExpression()
  {
    EFAndExpressionImpl efAndExpression = new EFAndExpressionImpl();
    return efAndExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFEqualExpression createEFEqualExpression()
  {
    EFEqualExpressionImpl efEqualExpression = new EFEqualExpressionImpl();
    return efEqualExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRelExpression createEFRelExpression()
  {
    EFRelExpressionImpl efRelExpression = new EFRelExpressionImpl();
    return efRelExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFAddExpression createEFAddExpression()
  {
    EFAddExpressionImpl efAddExpression = new EFAddExpressionImpl();
    return efAddExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFMultExpression createEFMultExpression()
  {
    EFMultExpressionImpl efMultExpression = new EFMultExpressionImpl();
    return efMultExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNotExpression createEFNotExpression()
  {
    EFNotExpressionImpl efNotExpression = new EFNotExpressionImpl();
    return efNotExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFMemberSelection createEFMemberSelection()
  {
    EFMemberSelectionImpl efMemberSelection = new EFMemberSelectionImpl();
    return efMemberSelection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFStringConstant createEFStringConstant()
  {
    EFStringConstantImpl efStringConstant = new EFStringConstantImpl();
    return efStringConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFIntConstant createEFIntConstant()
  {
    EFIntConstantImpl efIntConstant = new EFIntConstantImpl();
    return efIntConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFBoolConstant createEFBoolConstant()
  {
    EFBoolConstantImpl efBoolConstant = new EFBoolConstantImpl();
    return efBoolConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFDirectionConstant createEFDirectionConstant()
  {
    EFDirectionConstantImpl efDirectionConstant = new EFDirectionConstantImpl();
    return efDirectionConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetworkProtocolConstant createEFNetworkProtocolConstant()
  {
    EFNetworkProtocolConstantImpl efNetworkProtocolConstant = new EFNetworkProtocolConstantImpl();
    return efNetworkProtocolConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFTransportProtocolConstant createEFTransportProtocolConstant()
  {
    EFTransportProtocolConstantImpl efTransportProtocolConstant = new EFTransportProtocolConstantImpl();
    return efTransportProtocolConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFApplicationProtocolConstant createEFApplicationProtocolConstant()
  {
    EFApplicationProtocolConstantImpl efApplicationProtocolConstant = new EFApplicationProtocolConstantImpl();
    return efApplicationProtocolConstant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFIPv6Constant createEFIPv6Constant()
  {
    EFIPv6ConstantImpl efiPv6Constant = new EFIPv6ConstantImpl();
    return efiPv6Constant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFIPv4Constant createEFIPv4Constant()
  {
    EFIPv4ConstantImpl efiPv4Constant = new EFIPv4ConstantImpl();
    return efiPv4Constant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFThis createEFThis()
  {
    EFThisImpl efThis = new EFThisImpl();
    return efThis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFSuper createEFSuper()
  {
    EFSuperImpl efSuper = new EFSuperImpl();
    return efSuper;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNew createEFNew()
  {
    EFNewImpl efNew = new EFNewImpl();
    return efNew;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFBracketsExpression createEFBracketsExpression()
  {
    EFBracketsExpressionImpl efBracketsExpression = new EFBracketsExpressionImpl();
    return efBracketsExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFFunctionCall createEFFunctionCall()
  {
    EFFunctionCallImpl efFunctionCall = new EFFunctionCallImpl();
    return efFunctionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFSymbolRef createEFSymbolRef()
  {
    EFSymbolRefImpl efSymbolRef = new EFSymbolRefImpl();
    return efSymbolRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFAllow createEFAllow()
  {
    EFAllowImpl efAllow = new EFAllowImpl();
    return efAllow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFDrop createEFDrop()
  {
    EFDropImpl efDrop = new EFDropImpl();
    return efDrop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFReject createEFReject()
  {
    EFRejectImpl efReject = new EFRejectImpl();
    return efReject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFWriteLog createEFWriteLog()
  {
    EFWriteLogImpl efWriteLog = new EFWriteLogImpl();
    return efWriteLog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFWriteLogLevel createEFWriteLogLevel()
  {
    EFWriteLogLevelImpl efWriteLogLevel = new EFWriteLogLevelImpl();
    return efWriteLogLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFGetTime createEFGetTime()
  {
    EFGetTimeImpl efGetTime = new EFGetTimeImpl();
    return efGetTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFGetPacketField createEFGetPacketField()
  {
    EFGetPacketFieldImpl efGetPacketField = new EFGetPacketFieldImpl();
    return efGetPacketField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFDefaultAction createEFDefaultActionFromString(EDataType eDataType, String initialValue)
  {
    EFDefaultAction result = EFDefaultAction.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFDefaultActionToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFNetworkNativeType createEFNetworkNativeTypeFromString(EDataType eDataType, String initialValue)
  {
    EFNetworkNativeType result = EFNetworkNativeType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFNetworkNativeTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFPrimitiveType createEFPrimitiveTypeFromString(EDataType eDataType, String initialValue)
  {
    EFPrimitiveType result = EFPrimitiveType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFPrimitiveTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFDirectionNativeType createEFDirectionNativeTypeFromString(EDataType eDataType, String initialValue)
  {
    EFDirectionNativeType result = EFDirectionNativeType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFDirectionNativeTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFLogLevel createEFLogLevelFromString(EDataType eDataType, String initialValue)
  {
    EFLogLevel result = EFLogLevel.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFLogLevelToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFRulesTypes createEFRulesTypesFromString(EDataType eDataType, String initialValue)
  {
    EFRulesTypes result = EFRulesTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertEFRulesTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NETWORKLAYERPROTOCOL createNETWORKLAYERPROTOCOLFromString(EDataType eDataType, String initialValue)
  {
    NETWORKLAYERPROTOCOL result = NETWORKLAYERPROTOCOL.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertNETWORKLAYERPROTOCOLToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TRANSPORTLAYERPROTOCOL createTRANSPORTLAYERPROTOCOLFromString(EDataType eDataType, String initialValue)
  {
    TRANSPORTLAYERPROTOCOL result = TRANSPORTLAYERPROTOCOL.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertTRANSPORTLAYERPROTOCOLToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public APPLICATIONLAYERPROTOCOL createAPPLICATIONLAYERPROTOCOLFromString(EDataType eDataType, String initialValue)
  {
    APPLICATIONLAYERPROTOCOL result = APPLICATIONLAYERPROTOCOL.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertAPPLICATIONLAYERPROTOCOLToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EasyWallPackage getEasyWallPackage()
  {
    return (EasyWallPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static EasyWallPackage getPackage()
  {
    return EasyWallPackage.eINSTANCE;
  }

} //EasyWallFactoryImpl
