/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.easywall.easyWall.EFAddExpression;
import org.xtext.example.easywall.easyWall.EFAllow;
import org.xtext.example.easywall.easyWall.EFAndExpression;
import org.xtext.example.easywall.easyWall.EFApplicationProtocolConstant;
import org.xtext.example.easywall.easyWall.EFAssignment;
import org.xtext.example.easywall.easyWall.EFBlock;
import org.xtext.example.easywall.easyWall.EFBoolConstant;
import org.xtext.example.easywall.easyWall.EFBracketsExpression;
import org.xtext.example.easywall.easyWall.EFBuiltinFunction;
import org.xtext.example.easywall.easyWall.EFDefaultAction;
import org.xtext.example.easywall.easyWall.EFDefaultPolicy;
import org.xtext.example.easywall.easyWall.EFDeny;
import org.xtext.example.easywall.easyWall.EFDirectionConstant;
import org.xtext.example.easywall.easyWall.EFDirectionNativeType;
import org.xtext.example.easywall.easyWall.EFEqualExpression;
import org.xtext.example.easywall.easyWall.EFExpression;
import org.xtext.example.easywall.easyWall.EFField;
import org.xtext.example.easywall.easyWall.EFFirewall;
import org.xtext.example.easywall.easyWall.EFFunctionCall;
import org.xtext.example.easywall.easyWall.EFGetPacketField;
import org.xtext.example.easywall.easyWall.EFGetTime;
import org.xtext.example.easywall.easyWall.EFHeader;
import org.xtext.example.easywall.easyWall.EFIPv4Constant;
import org.xtext.example.easywall.easyWall.EFIPv6Constant;
import org.xtext.example.easywall.easyWall.EFIfStatement;
import org.xtext.example.easywall.easyWall.EFImports;
import org.xtext.example.easywall.easyWall.EFIntConstant;
import org.xtext.example.easywall.easyWall.EFLogLevel;
import org.xtext.example.easywall.easyWall.EFMember;
import org.xtext.example.easywall.easyWall.EFMemberSelection;
import org.xtext.example.easywall.easyWall.EFMethod;
import org.xtext.example.easywall.easyWall.EFMultExpression;
import org.xtext.example.easywall.easyWall.EFNetportConstant;
import org.xtext.example.easywall.easyWall.EFNetworkConstant;
import org.xtext.example.easywall.easyWall.EFNetworkNativeType;
import org.xtext.example.easywall.easyWall.EFNetworkProtocolConstant;
import org.xtext.example.easywall.easyWall.EFNew;
import org.xtext.example.easywall.easyWall.EFNotExpression;
import org.xtext.example.easywall.easyWall.EFOrExpression;
import org.xtext.example.easywall.easyWall.EFParameter;
import org.xtext.example.easywall.easyWall.EFPrimitiveType;
import org.xtext.example.easywall.easyWall.EFProgram;
import org.xtext.example.easywall.easyWall.EFRelExpression;
import org.xtext.example.easywall.easyWall.EFReturn;
import org.xtext.example.easywall.easyWall.EFRule;
import org.xtext.example.easywall.easyWall.EFRuleClass;
import org.xtext.example.easywall.easyWall.EFRuleReference;
import org.xtext.example.easywall.easyWall.EFRulesTypes;
import org.xtext.example.easywall.easyWall.EFStatement;
import org.xtext.example.easywall.easyWall.EFStringConstant;
import org.xtext.example.easywall.easyWall.EFSuper;
import org.xtext.example.easywall.easyWall.EFSymbolRef;
import org.xtext.example.easywall.easyWall.EFThis;
import org.xtext.example.easywall.easyWall.EFTransportProtocolConstant;
import org.xtext.example.easywall.easyWall.EFVariableDeclaration;
import org.xtext.example.easywall.easyWall.EFWriteLog;
import org.xtext.example.easywall.easyWall.EFWriteLogLevel;
import org.xtext.example.easywall.easyWall.EasyWallFactory;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EasyWallPackageImpl extends EPackageImpl implements EasyWallPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efProgramEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efHeaderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efImportsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efFirewallEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efDefaultPolicyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efRuleReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efMemberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efVariableDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efMethodEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efIfStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efBuiltinFunctionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efRuleClassEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efNetworkConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efAssignmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efOrExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efAndExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efEqualExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efRelExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efAddExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efMultExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efNotExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efMemberSelectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efStringConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efIntConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efBoolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efDirectionConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efNetworkProtocolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efTransportProtocolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efApplicationProtocolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efiPv6ConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efiPv4ConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efNetportConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efThisEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efSuperEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efNewEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efBracketsExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efFunctionCallEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efSymbolRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efAllowEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efDenyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efWriteLogEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efWriteLogLevelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efGetTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass efGetPacketFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efDefaultActionEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efNetworkNativeTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efPrimitiveTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efDirectionNativeTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efLogLevelEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum efRulesTypesEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum networklayerprotocolEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum transportlayerprotocolEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum applicationlayerprotocolEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.easywall.easyWall.EasyWallPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private EasyWallPackageImpl()
  {
    super(eNS_URI, EasyWallFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link EasyWallPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static EasyWallPackage init()
  {
    if (isInited) return (EasyWallPackage)EPackage.Registry.INSTANCE.getEPackage(EasyWallPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredEasyWallPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    EasyWallPackageImpl theEasyWallPackage = registeredEasyWallPackage instanceof EasyWallPackageImpl ? (EasyWallPackageImpl)registeredEasyWallPackage : new EasyWallPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theEasyWallPackage.createPackageContents();

    // Initialize created meta-data
    theEasyWallPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theEasyWallPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(EasyWallPackage.eNS_URI, theEasyWallPackage);
    return theEasyWallPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFProgram()
  {
    return efProgramEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFProgram_Header()
  {
    return (EReference)efProgramEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFProgram_Rules()
  {
    return (EReference)efProgramEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFProgram_Firewall()
  {
    return (EReference)efProgramEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFHeader()
  {
    return efHeaderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFHeader_Name()
  {
    return (EAttribute)efHeaderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFHeader_Imports()
  {
    return (EReference)efHeaderEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFImports()
  {
    return efImportsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFImports_ImportedNamespace()
  {
    return (EAttribute)efImportsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFFirewall()
  {
    return efFirewallEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFFirewall_Name()
  {
    return (EAttribute)efFirewallEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFFirewall_DefaultPolicy()
  {
    return (EReference)efFirewallEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFFirewall_Members()
  {
    return (EReference)efFirewallEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFFirewall_RuleRefs()
  {
    return (EReference)efFirewallEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFDefaultPolicy()
  {
    return efDefaultPolicyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFDefaultPolicy_Action()
  {
    return (EAttribute)efDefaultPolicyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFRuleReference()
  {
    return efRuleReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFRuleReference_Rule()
  {
    return (EReference)efRuleReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFMember()
  {
    return efMemberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFMember_Name()
  {
    return (EAttribute)efMemberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMember_Ruletype()
  {
    return (EReference)efMemberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFMember_Nativetype()
  {
    return (EAttribute)efMemberEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFMember_Primitivetype()
  {
    return (EAttribute)efMemberEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFField()
  {
    return efFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFField_Expression()
  {
    return (EReference)efFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFVariableDeclaration()
  {
    return efVariableDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFVariableDeclaration_Name()
  {
    return (EAttribute)efVariableDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFVariableDeclaration_Ruletype()
  {
    return (EReference)efVariableDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFVariableDeclaration_Nativetype()
  {
    return (EAttribute)efVariableDeclarationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFVariableDeclaration_Primitivetype()
  {
    return (EAttribute)efVariableDeclarationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFVariableDeclaration_Expression()
  {
    return (EReference)efVariableDeclarationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFMethod()
  {
    return efMethodEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMethod_Params()
  {
    return (EReference)efMethodEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFMethod_Void()
  {
    return (EAttribute)efMethodEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMethod_Body()
  {
    return (EReference)efMethodEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFParameter()
  {
    return efParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFParameter_Name()
  {
    return (EAttribute)efParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFParameter_Ruletype()
  {
    return (EReference)efParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFParameter_Nativetype()
  {
    return (EAttribute)efParameterEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFParameter_Primitivetype()
  {
    return (EAttribute)efParameterEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFBlock()
  {
    return efBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFBlock_Statements()
  {
    return (EReference)efBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFStatement()
  {
    return efStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFReturn()
  {
    return efReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFReturn_Expression()
  {
    return (EReference)efReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFIfStatement()
  {
    return efIfStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFIfStatement_Expression()
  {
    return (EReference)efIfStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFIfStatement_ThenBlock()
  {
    return (EReference)efIfStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFIfStatement_ElseBlock()
  {
    return (EReference)efIfStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFExpression()
  {
    return efExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFBuiltinFunction()
  {
    return efBuiltinFunctionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFRule()
  {
    return efRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFRule_Rules()
  {
    return (EReference)efRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFRuleClass()
  {
    return efRuleClassEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFRuleClass_Name()
  {
    return (EAttribute)efRuleClassEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFRuleClass_Type()
  {
    return (EAttribute)efRuleClassEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFRuleClass_Members()
  {
    return (EReference)efRuleClassEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFNetworkConstant()
  {
    return efNetworkConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFNetworkConstant_Network()
  {
    return (EReference)efNetworkConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetworkConstant_Varip()
  {
    return (EAttribute)efNetworkConstantEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetworkConstant_Varnetmask()
  {
    return (EAttribute)efNetworkConstantEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetworkConstant_Rawip()
  {
    return (EAttribute)efNetworkConstantEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetworkConstant_Rawnetmask()
  {
    return (EAttribute)efNetworkConstantEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFAssignment()
  {
    return efAssignmentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAssignment_Left()
  {
    return (EReference)efAssignmentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAssignment_Right()
  {
    return (EReference)efAssignmentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFOrExpression()
  {
    return efOrExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFOrExpression_Left()
  {
    return (EReference)efOrExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFOrExpression_Right()
  {
    return (EReference)efOrExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFAndExpression()
  {
    return efAndExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAndExpression_Left()
  {
    return (EReference)efAndExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAndExpression_Right()
  {
    return (EReference)efAndExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFEqualExpression()
  {
    return efEqualExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFEqualExpression_Left()
  {
    return (EReference)efEqualExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFEqualExpression_Right()
  {
    return (EReference)efEqualExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFRelExpression()
  {
    return efRelExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFRelExpression_Left()
  {
    return (EReference)efRelExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFRelExpression_Right()
  {
    return (EReference)efRelExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFAddExpression()
  {
    return efAddExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAddExpression_Left()
  {
    return (EReference)efAddExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFAddExpression_Right()
  {
    return (EReference)efAddExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFMultExpression()
  {
    return efMultExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMultExpression_Left()
  {
    return (EReference)efMultExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMultExpression_Right()
  {
    return (EReference)efMultExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFNotExpression()
  {
    return efNotExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFNotExpression_Expression()
  {
    return (EReference)efNotExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFMemberSelection()
  {
    return efMemberSelectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMemberSelection_Receiver()
  {
    return (EReference)efMemberSelectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMemberSelection_Member()
  {
    return (EReference)efMemberSelectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFMemberSelection_Args()
  {
    return (EReference)efMemberSelectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFStringConstant()
  {
    return efStringConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFStringConstant_Value()
  {
    return (EAttribute)efStringConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFIntConstant()
  {
    return efIntConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFIntConstant_Value()
  {
    return (EAttribute)efIntConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFBoolConstant()
  {
    return efBoolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFBoolConstant_Value()
  {
    return (EAttribute)efBoolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFDirectionConstant()
  {
    return efDirectionConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFDirectionConstant_Direction()
  {
    return (EAttribute)efDirectionConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFNetworkProtocolConstant()
  {
    return efNetworkProtocolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetworkProtocolConstant_Protocol()
  {
    return (EAttribute)efNetworkProtocolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFTransportProtocolConstant()
  {
    return efTransportProtocolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFTransportProtocolConstant_Protocol()
  {
    return (EAttribute)efTransportProtocolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFApplicationProtocolConstant()
  {
    return efApplicationProtocolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFApplicationProtocolConstant_Protocol()
  {
    return (EAttribute)efApplicationProtocolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFIPv6Constant()
  {
    return efiPv6ConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFIPv6Constant_Ipv6()
  {
    return (EAttribute)efiPv6ConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFIPv4Constant()
  {
    return efiPv4ConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFIPv4Constant_Ipv4()
  {
    return (EAttribute)efiPv4ConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFIPv4Constant_Any()
  {
    return (EAttribute)efiPv4ConstantEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFIPv4Constant_Localhost()
  {
    return (EAttribute)efiPv4ConstantEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFNetportConstant()
  {
    return efNetportConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFNetportConstant_Netport()
  {
    return (EAttribute)efNetportConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFThis()
  {
    return efThisEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFSuper()
  {
    return efSuperEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFNew()
  {
    return efNewEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFNew_Type()
  {
    return (EReference)efNewEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFBracketsExpression()
  {
    return efBracketsExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFBracketsExpression_Expression()
  {
    return (EReference)efBracketsExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFFunctionCall()
  {
    return efFunctionCallEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFFunctionCall_FunctionName()
  {
    return (EAttribute)efFunctionCallEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFFunctionCall_Args()
  {
    return (EReference)efFunctionCallEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFSymbolRef()
  {
    return efSymbolRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFSymbolRef_Symbol()
  {
    return (EAttribute)efSymbolRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFAllow()
  {
    return efAllowEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFDeny()
  {
    return efDenyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFWriteLog()
  {
    return efWriteLogEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFWriteLog_Message()
  {
    return (EReference)efWriteLogEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFWriteLogLevel()
  {
    return efWriteLogLevelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFWriteLogLevel_Level()
  {
    return (EAttribute)efWriteLogLevelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEFWriteLogLevel_Message()
  {
    return (EReference)efWriteLogLevelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFGetTime()
  {
    return efGetTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEFGetPacketField()
  {
    return efGetPacketFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEFGetPacketField_Field()
  {
    return (EAttribute)efGetPacketFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFDefaultAction()
  {
    return efDefaultActionEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFNetworkNativeType()
  {
    return efNetworkNativeTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFPrimitiveType()
  {
    return efPrimitiveTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFDirectionNativeType()
  {
    return efDirectionNativeTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFLogLevel()
  {
    return efLogLevelEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getEFRulesTypes()
  {
    return efRulesTypesEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getNETWORKLAYERPROTOCOL()
  {
    return networklayerprotocolEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getTRANSPORTLAYERPROTOCOL()
  {
    return transportlayerprotocolEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getAPPLICATIONLAYERPROTOCOL()
  {
    return applicationlayerprotocolEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EasyWallFactory getEasyWallFactory()
  {
    return (EasyWallFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    efProgramEClass = createEClass(EF_PROGRAM);
    createEReference(efProgramEClass, EF_PROGRAM__HEADER);
    createEReference(efProgramEClass, EF_PROGRAM__RULES);
    createEReference(efProgramEClass, EF_PROGRAM__FIREWALL);

    efHeaderEClass = createEClass(EF_HEADER);
    createEAttribute(efHeaderEClass, EF_HEADER__NAME);
    createEReference(efHeaderEClass, EF_HEADER__IMPORTS);

    efImportsEClass = createEClass(EF_IMPORTS);
    createEAttribute(efImportsEClass, EF_IMPORTS__IMPORTED_NAMESPACE);

    efFirewallEClass = createEClass(EF_FIREWALL);
    createEAttribute(efFirewallEClass, EF_FIREWALL__NAME);
    createEReference(efFirewallEClass, EF_FIREWALL__DEFAULT_POLICY);
    createEReference(efFirewallEClass, EF_FIREWALL__MEMBERS);
    createEReference(efFirewallEClass, EF_FIREWALL__RULE_REFS);

    efDefaultPolicyEClass = createEClass(EF_DEFAULT_POLICY);
    createEAttribute(efDefaultPolicyEClass, EF_DEFAULT_POLICY__ACTION);

    efRuleReferenceEClass = createEClass(EF_RULE_REFERENCE);
    createEReference(efRuleReferenceEClass, EF_RULE_REFERENCE__RULE);

    efMemberEClass = createEClass(EF_MEMBER);
    createEAttribute(efMemberEClass, EF_MEMBER__NAME);
    createEReference(efMemberEClass, EF_MEMBER__RULETYPE);
    createEAttribute(efMemberEClass, EF_MEMBER__NATIVETYPE);
    createEAttribute(efMemberEClass, EF_MEMBER__PRIMITIVETYPE);

    efFieldEClass = createEClass(EF_FIELD);
    createEReference(efFieldEClass, EF_FIELD__EXPRESSION);

    efVariableDeclarationEClass = createEClass(EF_VARIABLE_DECLARATION);
    createEAttribute(efVariableDeclarationEClass, EF_VARIABLE_DECLARATION__NAME);
    createEReference(efVariableDeclarationEClass, EF_VARIABLE_DECLARATION__RULETYPE);
    createEAttribute(efVariableDeclarationEClass, EF_VARIABLE_DECLARATION__NATIVETYPE);
    createEAttribute(efVariableDeclarationEClass, EF_VARIABLE_DECLARATION__PRIMITIVETYPE);
    createEReference(efVariableDeclarationEClass, EF_VARIABLE_DECLARATION__EXPRESSION);

    efMethodEClass = createEClass(EF_METHOD);
    createEReference(efMethodEClass, EF_METHOD__PARAMS);
    createEAttribute(efMethodEClass, EF_METHOD__VOID);
    createEReference(efMethodEClass, EF_METHOD__BODY);

    efParameterEClass = createEClass(EF_PARAMETER);
    createEAttribute(efParameterEClass, EF_PARAMETER__NAME);
    createEReference(efParameterEClass, EF_PARAMETER__RULETYPE);
    createEAttribute(efParameterEClass, EF_PARAMETER__NATIVETYPE);
    createEAttribute(efParameterEClass, EF_PARAMETER__PRIMITIVETYPE);

    efBlockEClass = createEClass(EF_BLOCK);
    createEReference(efBlockEClass, EF_BLOCK__STATEMENTS);

    efStatementEClass = createEClass(EF_STATEMENT);

    efReturnEClass = createEClass(EF_RETURN);
    createEReference(efReturnEClass, EF_RETURN__EXPRESSION);

    efIfStatementEClass = createEClass(EF_IF_STATEMENT);
    createEReference(efIfStatementEClass, EF_IF_STATEMENT__EXPRESSION);
    createEReference(efIfStatementEClass, EF_IF_STATEMENT__THEN_BLOCK);
    createEReference(efIfStatementEClass, EF_IF_STATEMENT__ELSE_BLOCK);

    efExpressionEClass = createEClass(EF_EXPRESSION);

    efBuiltinFunctionEClass = createEClass(EF_BUILTIN_FUNCTION);

    efRuleEClass = createEClass(EF_RULE);
    createEReference(efRuleEClass, EF_RULE__RULES);

    efRuleClassEClass = createEClass(EF_RULE_CLASS);
    createEAttribute(efRuleClassEClass, EF_RULE_CLASS__NAME);
    createEAttribute(efRuleClassEClass, EF_RULE_CLASS__TYPE);
    createEReference(efRuleClassEClass, EF_RULE_CLASS__MEMBERS);

    efNetworkConstantEClass = createEClass(EF_NETWORK_CONSTANT);
    createEReference(efNetworkConstantEClass, EF_NETWORK_CONSTANT__NETWORK);
    createEAttribute(efNetworkConstantEClass, EF_NETWORK_CONSTANT__VARIP);
    createEAttribute(efNetworkConstantEClass, EF_NETWORK_CONSTANT__VARNETMASK);
    createEAttribute(efNetworkConstantEClass, EF_NETWORK_CONSTANT__RAWIP);
    createEAttribute(efNetworkConstantEClass, EF_NETWORK_CONSTANT__RAWNETMASK);

    efAssignmentEClass = createEClass(EF_ASSIGNMENT);
    createEReference(efAssignmentEClass, EF_ASSIGNMENT__LEFT);
    createEReference(efAssignmentEClass, EF_ASSIGNMENT__RIGHT);

    efOrExpressionEClass = createEClass(EF_OR_EXPRESSION);
    createEReference(efOrExpressionEClass, EF_OR_EXPRESSION__LEFT);
    createEReference(efOrExpressionEClass, EF_OR_EXPRESSION__RIGHT);

    efAndExpressionEClass = createEClass(EF_AND_EXPRESSION);
    createEReference(efAndExpressionEClass, EF_AND_EXPRESSION__LEFT);
    createEReference(efAndExpressionEClass, EF_AND_EXPRESSION__RIGHT);

    efEqualExpressionEClass = createEClass(EF_EQUAL_EXPRESSION);
    createEReference(efEqualExpressionEClass, EF_EQUAL_EXPRESSION__LEFT);
    createEReference(efEqualExpressionEClass, EF_EQUAL_EXPRESSION__RIGHT);

    efRelExpressionEClass = createEClass(EF_REL_EXPRESSION);
    createEReference(efRelExpressionEClass, EF_REL_EXPRESSION__LEFT);
    createEReference(efRelExpressionEClass, EF_REL_EXPRESSION__RIGHT);

    efAddExpressionEClass = createEClass(EF_ADD_EXPRESSION);
    createEReference(efAddExpressionEClass, EF_ADD_EXPRESSION__LEFT);
    createEReference(efAddExpressionEClass, EF_ADD_EXPRESSION__RIGHT);

    efMultExpressionEClass = createEClass(EF_MULT_EXPRESSION);
    createEReference(efMultExpressionEClass, EF_MULT_EXPRESSION__LEFT);
    createEReference(efMultExpressionEClass, EF_MULT_EXPRESSION__RIGHT);

    efNotExpressionEClass = createEClass(EF_NOT_EXPRESSION);
    createEReference(efNotExpressionEClass, EF_NOT_EXPRESSION__EXPRESSION);

    efMemberSelectionEClass = createEClass(EF_MEMBER_SELECTION);
    createEReference(efMemberSelectionEClass, EF_MEMBER_SELECTION__RECEIVER);
    createEReference(efMemberSelectionEClass, EF_MEMBER_SELECTION__MEMBER);
    createEReference(efMemberSelectionEClass, EF_MEMBER_SELECTION__ARGS);

    efStringConstantEClass = createEClass(EF_STRING_CONSTANT);
    createEAttribute(efStringConstantEClass, EF_STRING_CONSTANT__VALUE);

    efIntConstantEClass = createEClass(EF_INT_CONSTANT);
    createEAttribute(efIntConstantEClass, EF_INT_CONSTANT__VALUE);

    efBoolConstantEClass = createEClass(EF_BOOL_CONSTANT);
    createEAttribute(efBoolConstantEClass, EF_BOOL_CONSTANT__VALUE);

    efDirectionConstantEClass = createEClass(EF_DIRECTION_CONSTANT);
    createEAttribute(efDirectionConstantEClass, EF_DIRECTION_CONSTANT__DIRECTION);

    efNetworkProtocolConstantEClass = createEClass(EF_NETWORK_PROTOCOL_CONSTANT);
    createEAttribute(efNetworkProtocolConstantEClass, EF_NETWORK_PROTOCOL_CONSTANT__PROTOCOL);

    efTransportProtocolConstantEClass = createEClass(EF_TRANSPORT_PROTOCOL_CONSTANT);
    createEAttribute(efTransportProtocolConstantEClass, EF_TRANSPORT_PROTOCOL_CONSTANT__PROTOCOL);

    efApplicationProtocolConstantEClass = createEClass(EF_APPLICATION_PROTOCOL_CONSTANT);
    createEAttribute(efApplicationProtocolConstantEClass, EF_APPLICATION_PROTOCOL_CONSTANT__PROTOCOL);

    efiPv6ConstantEClass = createEClass(EFI_PV6_CONSTANT);
    createEAttribute(efiPv6ConstantEClass, EFI_PV6_CONSTANT__IPV6);

    efiPv4ConstantEClass = createEClass(EFI_PV4_CONSTANT);
    createEAttribute(efiPv4ConstantEClass, EFI_PV4_CONSTANT__IPV4);
    createEAttribute(efiPv4ConstantEClass, EFI_PV4_CONSTANT__ANY);
    createEAttribute(efiPv4ConstantEClass, EFI_PV4_CONSTANT__LOCALHOST);

    efNetportConstantEClass = createEClass(EF_NETPORT_CONSTANT);
    createEAttribute(efNetportConstantEClass, EF_NETPORT_CONSTANT__NETPORT);

    efThisEClass = createEClass(EF_THIS);

    efSuperEClass = createEClass(EF_SUPER);

    efNewEClass = createEClass(EF_NEW);
    createEReference(efNewEClass, EF_NEW__TYPE);

    efBracketsExpressionEClass = createEClass(EF_BRACKETS_EXPRESSION);
    createEReference(efBracketsExpressionEClass, EF_BRACKETS_EXPRESSION__EXPRESSION);

    efFunctionCallEClass = createEClass(EF_FUNCTION_CALL);
    createEAttribute(efFunctionCallEClass, EF_FUNCTION_CALL__FUNCTION_NAME);
    createEReference(efFunctionCallEClass, EF_FUNCTION_CALL__ARGS);

    efSymbolRefEClass = createEClass(EF_SYMBOL_REF);
    createEAttribute(efSymbolRefEClass, EF_SYMBOL_REF__SYMBOL);

    efAllowEClass = createEClass(EF_ALLOW);

    efDenyEClass = createEClass(EF_DENY);

    efWriteLogEClass = createEClass(EF_WRITE_LOG);
    createEReference(efWriteLogEClass, EF_WRITE_LOG__MESSAGE);

    efWriteLogLevelEClass = createEClass(EF_WRITE_LOG_LEVEL);
    createEAttribute(efWriteLogLevelEClass, EF_WRITE_LOG_LEVEL__LEVEL);
    createEReference(efWriteLogLevelEClass, EF_WRITE_LOG_LEVEL__MESSAGE);

    efGetTimeEClass = createEClass(EF_GET_TIME);

    efGetPacketFieldEClass = createEClass(EF_GET_PACKET_FIELD);
    createEAttribute(efGetPacketFieldEClass, EF_GET_PACKET_FIELD__FIELD);

    // Create enums
    efDefaultActionEEnum = createEEnum(EF_DEFAULT_ACTION);
    efNetworkNativeTypeEEnum = createEEnum(EF_NETWORK_NATIVE_TYPE);
    efPrimitiveTypeEEnum = createEEnum(EF_PRIMITIVE_TYPE);
    efDirectionNativeTypeEEnum = createEEnum(EF_DIRECTION_NATIVE_TYPE);
    efLogLevelEEnum = createEEnum(EF_LOG_LEVEL);
    efRulesTypesEEnum = createEEnum(EF_RULES_TYPES);
    networklayerprotocolEEnum = createEEnum(NETWORKLAYERPROTOCOL);
    transportlayerprotocolEEnum = createEEnum(TRANSPORTLAYERPROTOCOL);
    applicationlayerprotocolEEnum = createEEnum(APPLICATIONLAYERPROTOCOL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    efFieldEClass.getESuperTypes().add(this.getEFMember());
    efFieldEClass.getESuperTypes().add(this.getEFStatement());
    efMethodEClass.getESuperTypes().add(this.getEFMember());
    efReturnEClass.getESuperTypes().add(this.getEFStatement());
    efIfStatementEClass.getESuperTypes().add(this.getEFStatement());
    efExpressionEClass.getESuperTypes().add(this.getEFStatement());
    efBuiltinFunctionEClass.getESuperTypes().add(this.getEFExpression());
    efNetworkConstantEClass.getESuperTypes().add(this.getEFExpression());
    efAssignmentEClass.getESuperTypes().add(this.getEFExpression());
    efOrExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efAndExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efEqualExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efRelExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efAddExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efMultExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efNotExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efMemberSelectionEClass.getESuperTypes().add(this.getEFExpression());
    efStringConstantEClass.getESuperTypes().add(this.getEFExpression());
    efIntConstantEClass.getESuperTypes().add(this.getEFExpression());
    efBoolConstantEClass.getESuperTypes().add(this.getEFExpression());
    efDirectionConstantEClass.getESuperTypes().add(this.getEFExpression());
    efNetworkProtocolConstantEClass.getESuperTypes().add(this.getEFExpression());
    efTransportProtocolConstantEClass.getESuperTypes().add(this.getEFExpression());
    efApplicationProtocolConstantEClass.getESuperTypes().add(this.getEFExpression());
    efiPv6ConstantEClass.getESuperTypes().add(this.getEFExpression());
    efiPv4ConstantEClass.getESuperTypes().add(this.getEFExpression());
    efNetportConstantEClass.getESuperTypes().add(this.getEFExpression());
    efThisEClass.getESuperTypes().add(this.getEFExpression());
    efSuperEClass.getESuperTypes().add(this.getEFExpression());
    efNewEClass.getESuperTypes().add(this.getEFExpression());
    efBracketsExpressionEClass.getESuperTypes().add(this.getEFExpression());
    efFunctionCallEClass.getESuperTypes().add(this.getEFExpression());
    efSymbolRefEClass.getESuperTypes().add(this.getEFExpression());
    efAllowEClass.getESuperTypes().add(this.getEFBuiltinFunction());
    efDenyEClass.getESuperTypes().add(this.getEFBuiltinFunction());
    efWriteLogEClass.getESuperTypes().add(this.getEFBuiltinFunction());
    efWriteLogLevelEClass.getESuperTypes().add(this.getEFBuiltinFunction());
    efGetTimeEClass.getESuperTypes().add(this.getEFBuiltinFunction());
    efGetPacketFieldEClass.getESuperTypes().add(this.getEFBuiltinFunction());

    // Initialize classes and features; add operations and parameters
    initEClass(efProgramEClass, EFProgram.class, "EFProgram", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFProgram_Header(), this.getEFHeader(), null, "header", null, 0, 1, EFProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFProgram_Rules(), this.getEFRule(), null, "rules", null, 0, -1, EFProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFProgram_Firewall(), this.getEFFirewall(), null, "firewall", null, 0, 1, EFProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efHeaderEClass, EFHeader.class, "EFHeader", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFHeader_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFHeader.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFHeader_Imports(), this.getEFImports(), null, "imports", null, 0, -1, EFHeader.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efImportsEClass, EFImports.class, "EFImports", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFImports_ImportedNamespace(), ecorePackage.getEString(), "importedNamespace", null, 0, 1, EFImports.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efFirewallEClass, EFFirewall.class, "EFFirewall", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFFirewall_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFFirewall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFFirewall_DefaultPolicy(), this.getEFDefaultPolicy(), null, "defaultPolicy", null, 0, 1, EFFirewall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFFirewall_Members(), this.getEFMember(), null, "members", null, 0, -1, EFFirewall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFFirewall_RuleRefs(), this.getEFRuleReference(), null, "ruleRefs", null, 0, -1, EFFirewall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efDefaultPolicyEClass, EFDefaultPolicy.class, "EFDefaultPolicy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFDefaultPolicy_Action(), this.getEFDefaultAction(), "action", null, 0, 1, EFDefaultPolicy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efRuleReferenceEClass, EFRuleReference.class, "EFRuleReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFRuleReference_Rule(), this.getEFRuleClass(), null, "rule", null, 0, 1, EFRuleReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efMemberEClass, EFMember.class, "EFMember", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFMember_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFMember_Ruletype(), this.getEFRuleClass(), null, "ruletype", null, 0, 1, EFMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFMember_Nativetype(), this.getEFNetworkNativeType(), "nativetype", null, 0, 1, EFMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFMember_Primitivetype(), this.getEFPrimitiveType(), "primitivetype", null, 0, 1, EFMember.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efFieldEClass, EFField.class, "EFField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFField_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efVariableDeclarationEClass, EFVariableDeclaration.class, "EFVariableDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFVariableDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFVariableDeclaration_Ruletype(), this.getEFRuleClass(), null, "ruletype", null, 0, 1, EFVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFVariableDeclaration_Nativetype(), this.getEFNetworkNativeType(), "nativetype", null, 0, 1, EFVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFVariableDeclaration_Primitivetype(), this.getEFPrimitiveType(), "primitivetype", null, 0, 1, EFVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFVariableDeclaration_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFVariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efMethodEClass, EFMethod.class, "EFMethod", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFMethod_Params(), this.getEFParameter(), null, "params", null, 0, -1, EFMethod.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFMethod_Void(), ecorePackage.getEString(), "void", null, 0, 1, EFMethod.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFMethod_Body(), this.getEFBlock(), null, "body", null, 0, 1, EFMethod.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efParameterEClass, EFParameter.class, "EFParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFParameter_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFParameter_Ruletype(), this.getEFRuleClass(), null, "ruletype", null, 0, 1, EFParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFParameter_Nativetype(), this.getEFNetworkNativeType(), "nativetype", null, 0, 1, EFParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFParameter_Primitivetype(), this.getEFPrimitiveType(), "primitivetype", null, 0, 1, EFParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efBlockEClass, EFBlock.class, "EFBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFBlock_Statements(), this.getEFStatement(), null, "statements", null, 0, -1, EFBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efStatementEClass, EFStatement.class, "EFStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efReturnEClass, EFReturn.class, "EFReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFReturn_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efIfStatementEClass, EFIfStatement.class, "EFIfStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFIfStatement_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFIfStatement_ThenBlock(), this.getEFBlock(), null, "thenBlock", null, 0, 1, EFIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFIfStatement_ElseBlock(), this.getEFBlock(), null, "elseBlock", null, 0, 1, EFIfStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efExpressionEClass, EFExpression.class, "EFExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efBuiltinFunctionEClass, EFBuiltinFunction.class, "EFBuiltinFunction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efRuleEClass, EFRule.class, "EFRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFRule_Rules(), this.getEFRuleClass(), null, "rules", null, 0, 1, EFRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efRuleClassEClass, EFRuleClass.class, "EFRuleClass", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFRuleClass_Name(), ecorePackage.getEString(), "name", null, 0, 1, EFRuleClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFRuleClass_Type(), this.getEFRulesTypes(), "type", null, 0, 1, EFRuleClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFRuleClass_Members(), this.getEFMember(), null, "members", null, 0, -1, EFRuleClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efNetworkConstantEClass, EFNetworkConstant.class, "EFNetworkConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFNetworkConstant_Network(), this.getEFNetworkConstant(), null, "network", null, 0, 1, EFNetworkConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFNetworkConstant_Varip(), ecorePackage.getEString(), "varip", null, 0, 1, EFNetworkConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFNetworkConstant_Varnetmask(), ecorePackage.getEString(), "varnetmask", null, 0, 1, EFNetworkConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFNetworkConstant_Rawip(), ecorePackage.getEString(), "rawip", null, 0, 1, EFNetworkConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFNetworkConstant_Rawnetmask(), ecorePackage.getEInt(), "rawnetmask", null, 0, 1, EFNetworkConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efAssignmentEClass, EFAssignment.class, "EFAssignment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFAssignment_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFAssignment.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFAssignment_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFAssignment.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efOrExpressionEClass, EFOrExpression.class, "EFOrExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFOrExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFOrExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFOrExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFOrExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efAndExpressionEClass, EFAndExpression.class, "EFAndExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFAndExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFAndExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFAndExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFAndExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efEqualExpressionEClass, EFEqualExpression.class, "EFEqualExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFEqualExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFEqualExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFEqualExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFEqualExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efRelExpressionEClass, EFRelExpression.class, "EFRelExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFRelExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFRelExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFRelExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFRelExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efAddExpressionEClass, EFAddExpression.class, "EFAddExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFAddExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFAddExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFAddExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFAddExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efMultExpressionEClass, EFMultExpression.class, "EFMultExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFMultExpression_Left(), this.getEFExpression(), null, "left", null, 0, 1, EFMultExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFMultExpression_Right(), this.getEFExpression(), null, "right", null, 0, 1, EFMultExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efNotExpressionEClass, EFNotExpression.class, "EFNotExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFNotExpression_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFNotExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efMemberSelectionEClass, EFMemberSelection.class, "EFMemberSelection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFMemberSelection_Receiver(), this.getEFExpression(), null, "receiver", null, 0, 1, EFMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFMemberSelection_Member(), this.getEFMember(), null, "member", null, 0, 1, EFMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFMemberSelection_Args(), this.getEFExpression(), null, "args", null, 0, -1, EFMemberSelection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efStringConstantEClass, EFStringConstant.class, "EFStringConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFStringConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, EFStringConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efIntConstantEClass, EFIntConstant.class, "EFIntConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFIntConstant_Value(), ecorePackage.getEInt(), "value", null, 0, 1, EFIntConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efBoolConstantEClass, EFBoolConstant.class, "EFBoolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFBoolConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, EFBoolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efDirectionConstantEClass, EFDirectionConstant.class, "EFDirectionConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFDirectionConstant_Direction(), this.getEFDirectionNativeType(), "direction", null, 0, 1, EFDirectionConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efNetworkProtocolConstantEClass, EFNetworkProtocolConstant.class, "EFNetworkProtocolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFNetworkProtocolConstant_Protocol(), this.getNETWORKLAYERPROTOCOL(), "protocol", null, 0, 1, EFNetworkProtocolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efTransportProtocolConstantEClass, EFTransportProtocolConstant.class, "EFTransportProtocolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFTransportProtocolConstant_Protocol(), this.getTRANSPORTLAYERPROTOCOL(), "protocol", null, 0, 1, EFTransportProtocolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efApplicationProtocolConstantEClass, EFApplicationProtocolConstant.class, "EFApplicationProtocolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFApplicationProtocolConstant_Protocol(), this.getAPPLICATIONLAYERPROTOCOL(), "protocol", null, 0, 1, EFApplicationProtocolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efiPv6ConstantEClass, EFIPv6Constant.class, "EFIPv6Constant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFIPv6Constant_Ipv6(), ecorePackage.getEString(), "ipv6", null, 0, 1, EFIPv6Constant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efiPv4ConstantEClass, EFIPv4Constant.class, "EFIPv4Constant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFIPv4Constant_Ipv4(), ecorePackage.getEString(), "ipv4", null, 0, 1, EFIPv4Constant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFIPv4Constant_Any(), ecorePackage.getEString(), "any", null, 0, 1, EFIPv4Constant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEFIPv4Constant_Localhost(), ecorePackage.getEString(), "localhost", null, 0, 1, EFIPv4Constant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efNetportConstantEClass, EFNetportConstant.class, "EFNetportConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFNetportConstant_Netport(), ecorePackage.getEInt(), "netport", null, 0, 1, EFNetportConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efThisEClass, EFThis.class, "EFThis", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efSuperEClass, EFSuper.class, "EFSuper", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efNewEClass, EFNew.class, "EFNew", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFNew_Type(), this.getEFRuleClass(), null, "type", null, 0, 1, EFNew.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efBracketsExpressionEClass, EFBracketsExpression.class, "EFBracketsExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFBracketsExpression_Expression(), this.getEFExpression(), null, "expression", null, 0, 1, EFBracketsExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efFunctionCallEClass, EFFunctionCall.class, "EFFunctionCall", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFFunctionCall_FunctionName(), ecorePackage.getEString(), "functionName", null, 0, 1, EFFunctionCall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFFunctionCall_Args(), this.getEFExpression(), null, "args", null, 0, -1, EFFunctionCall.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efSymbolRefEClass, EFSymbolRef.class, "EFSymbolRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFSymbolRef_Symbol(), ecorePackage.getEString(), "symbol", null, 0, 1, EFSymbolRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efAllowEClass, EFAllow.class, "EFAllow", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efDenyEClass, EFDeny.class, "EFDeny", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efWriteLogEClass, EFWriteLog.class, "EFWriteLog", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEFWriteLog_Message(), this.getEFExpression(), null, "message", null, 0, 1, EFWriteLog.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efWriteLogLevelEClass, EFWriteLogLevel.class, "EFWriteLogLevel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFWriteLogLevel_Level(), this.getEFLogLevel(), "level", null, 0, 1, EFWriteLogLevel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEFWriteLogLevel_Message(), this.getEFExpression(), null, "message", null, 0, 1, EFWriteLogLevel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(efGetTimeEClass, EFGetTime.class, "EFGetTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(efGetPacketFieldEClass, EFGetPacketField.class, "EFGetPacketField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEFGetPacketField_Field(), ecorePackage.getEString(), "field", null, 0, 1, EFGetPacketField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(efDefaultActionEEnum, EFDefaultAction.class, "EFDefaultAction");
    addEEnumLiteral(efDefaultActionEEnum, EFDefaultAction.ALLOW);
    addEEnumLiteral(efDefaultActionEEnum, EFDefaultAction.DENY);

    initEEnum(efNetworkNativeTypeEEnum, EFNetworkNativeType.class, "EFNetworkNativeType");
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.NETWORK);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.IPV4);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.IPV6);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.PORT);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.PROTOCOL);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.DIRECTION);
    addEEnumLiteral(efNetworkNativeTypeEEnum, EFNetworkNativeType.NETMASK);

    initEEnum(efPrimitiveTypeEEnum, EFPrimitiveType.class, "EFPrimitiveType");
    addEEnumLiteral(efPrimitiveTypeEEnum, EFPrimitiveType.INT);
    addEEnumLiteral(efPrimitiveTypeEEnum, EFPrimitiveType.STRING);
    addEEnumLiteral(efPrimitiveTypeEEnum, EFPrimitiveType.BOOL);

    initEEnum(efDirectionNativeTypeEEnum, EFDirectionNativeType.class, "EFDirectionNativeType");
    addEEnumLiteral(efDirectionNativeTypeEEnum, EFDirectionNativeType.IN);
    addEEnumLiteral(efDirectionNativeTypeEEnum, EFDirectionNativeType.OUT);
    addEEnumLiteral(efDirectionNativeTypeEEnum, EFDirectionNativeType.FORWARD);

    initEEnum(efLogLevelEEnum, EFLogLevel.class, "EFLogLevel");
    addEEnumLiteral(efLogLevelEEnum, EFLogLevel.DEBUG);
    addEEnumLiteral(efLogLevelEEnum, EFLogLevel.INFO);
    addEEnumLiteral(efLogLevelEEnum, EFLogLevel.WARNING);
    addEEnumLiteral(efLogLevelEEnum, EFLogLevel.ERROR);
    addEEnumLiteral(efLogLevelEEnum, EFLogLevel.CRITICAL);

    initEEnum(efRulesTypesEEnum, EFRulesTypes.class, "EFRulesTypes");
    addEEnumLiteral(efRulesTypesEEnum, EFRulesTypes.IPLEVEL);
    addEEnumLiteral(efRulesTypesEEnum, EFRulesTypes.TRANSPLEVEL);
    addEEnumLiteral(efRulesTypesEEnum, EFRulesTypes.APPLEVEL);

    initEEnum(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.class, "NETWORKLAYERPROTOCOL");
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.IPV4);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.IPV6);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.ARP);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.ICMP);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.NAT);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.RIP);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.OSPF);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.IPSEC);
    addEEnumLiteral(networklayerprotocolEEnum, org.xtext.example.easywall.easyWall.NETWORKLAYERPROTOCOL.IGMP);

    initEEnum(transportlayerprotocolEEnum, org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL.class, "TRANSPORTLAYERPROTOCOL");
    addEEnumLiteral(transportlayerprotocolEEnum, org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL.UDP);
    addEEnumLiteral(transportlayerprotocolEEnum, org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL.TCP);
    addEEnumLiteral(transportlayerprotocolEEnum, org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL.QUIC);
    addEEnumLiteral(transportlayerprotocolEEnum, org.xtext.example.easywall.easyWall.TRANSPORTLAYERPROTOCOL.SCTP);

    initEEnum(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.class, "APPLICATIONLAYERPROTOCOL");
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.HTTP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.HTTPS);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.SMTP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.POP3);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.IMAP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.FTP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.TFTP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.SNMP);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.TELNET);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.SSH);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.DNS);
    addEEnumLiteral(applicationlayerprotocolEEnum, org.xtext.example.easywall.easyWall.APPLICATIONLAYERPROTOCOL.DHCP);

    // Create resource
    createResource(eNS_URI);
  }

} //EasyWallPackageImpl
