/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.easywall.easyWall.EFDrop;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Drop</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EFDropImpl extends EFBuiltinFunctionImpl implements EFDrop
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFDropImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_DROP;
  }

} //EFDropImpl
