/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.easywall.easyWall.EFDefaultPolicy;
import org.xtext.example.easywall.easyWall.EFFirewall;
import org.xtext.example.easywall.easyWall.EFMember;
import org.xtext.example.easywall.easyWall.EFRuleReference;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Firewall</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFFirewallImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFFirewallImpl#getDefaultPolicy <em>Default Policy</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFFirewallImpl#getMembers <em>Members</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFFirewallImpl#getRuleRefs <em>Rule Refs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFFirewallImpl extends MinimalEObjectImpl.Container implements EFFirewall
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDefaultPolicy() <em>Default Policy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultPolicy()
   * @generated
   * @ordered
   */
  protected EFDefaultPolicy defaultPolicy;

  /**
   * The cached value of the '{@link #getMembers() <em>Members</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMembers()
   * @generated
   * @ordered
   */
  protected EList<EFMember> members;

  /**
   * The cached value of the '{@link #getRuleRefs() <em>Rule Refs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRuleRefs()
   * @generated
   * @ordered
   */
  protected EList<EFRuleReference> ruleRefs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFFirewallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_FIREWALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_FIREWALL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFDefaultPolicy getDefaultPolicy()
  {
    return defaultPolicy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefaultPolicy(EFDefaultPolicy newDefaultPolicy, NotificationChain msgs)
  {
    EFDefaultPolicy oldDefaultPolicy = defaultPolicy;
    defaultPolicy = newDefaultPolicy;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY, oldDefaultPolicy, newDefaultPolicy);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefaultPolicy(EFDefaultPolicy newDefaultPolicy)
  {
    if (newDefaultPolicy != defaultPolicy)
    {
      NotificationChain msgs = null;
      if (defaultPolicy != null)
        msgs = ((InternalEObject)defaultPolicy).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY, null, msgs);
      if (newDefaultPolicy != null)
        msgs = ((InternalEObject)newDefaultPolicy).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY, null, msgs);
      msgs = basicSetDefaultPolicy(newDefaultPolicy, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY, newDefaultPolicy, newDefaultPolicy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EFMember> getMembers()
  {
    if (members == null)
    {
      members = new EObjectContainmentEList<EFMember>(EFMember.class, this, EasyWallPackage.EF_FIREWALL__MEMBERS);
    }
    return members;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EFRuleReference> getRuleRefs()
  {
    if (ruleRefs == null)
    {
      ruleRefs = new EObjectContainmentEList<EFRuleReference>(EFRuleReference.class, this, EasyWallPackage.EF_FIREWALL__RULE_REFS);
    }
    return ruleRefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY:
        return basicSetDefaultPolicy(null, msgs);
      case EasyWallPackage.EF_FIREWALL__MEMBERS:
        return ((InternalEList<?>)getMembers()).basicRemove(otherEnd, msgs);
      case EasyWallPackage.EF_FIREWALL__RULE_REFS:
        return ((InternalEList<?>)getRuleRefs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_FIREWALL__NAME:
        return getName();
      case EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY:
        return getDefaultPolicy();
      case EasyWallPackage.EF_FIREWALL__MEMBERS:
        return getMembers();
      case EasyWallPackage.EF_FIREWALL__RULE_REFS:
        return getRuleRefs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_FIREWALL__NAME:
        setName((String)newValue);
        return;
      case EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY:
        setDefaultPolicy((EFDefaultPolicy)newValue);
        return;
      case EasyWallPackage.EF_FIREWALL__MEMBERS:
        getMembers().clear();
        getMembers().addAll((Collection<? extends EFMember>)newValue);
        return;
      case EasyWallPackage.EF_FIREWALL__RULE_REFS:
        getRuleRefs().clear();
        getRuleRefs().addAll((Collection<? extends EFRuleReference>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_FIREWALL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY:
        setDefaultPolicy((EFDefaultPolicy)null);
        return;
      case EasyWallPackage.EF_FIREWALL__MEMBERS:
        getMembers().clear();
        return;
      case EasyWallPackage.EF_FIREWALL__RULE_REFS:
        getRuleRefs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_FIREWALL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EasyWallPackage.EF_FIREWALL__DEFAULT_POLICY:
        return defaultPolicy != null;
      case EasyWallPackage.EF_FIREWALL__MEMBERS:
        return members != null && !members.isEmpty();
      case EasyWallPackage.EF_FIREWALL__RULE_REFS:
        return ruleRefs != null && !ruleRefs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EFFirewallImpl
