/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.easywall.easyWall.EFFirewall;
import org.xtext.example.easywall.easyWall.EFHeader;
import org.xtext.example.easywall.easyWall.EFImports;
import org.xtext.example.easywall.easyWall.EFRule;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Header</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFHeaderImpl#getRules <em>Rules</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFHeaderImpl#getFirewall <em>Firewall</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFHeaderImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFHeaderImpl#getImports <em>Imports</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFHeaderImpl extends EFProgramImpl implements EFHeader
{
  /**
   * The cached value of the '{@link #getRules() <em>Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRules()
   * @generated
   * @ordered
   */
  protected EList<EFRule> rules;

  /**
   * The cached value of the '{@link #getFirewall() <em>Firewall</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirewall()
   * @generated
   * @ordered
   */
  protected EFFirewall firewall;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<EFImports> imports;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFHeaderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_HEADER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EFRule> getRules()
  {
    if (rules == null)
    {
      rules = new EObjectContainmentEList<EFRule>(EFRule.class, this, EasyWallPackage.EF_HEADER__RULES);
    }
    return rules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFFirewall getFirewall()
  {
    return firewall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFirewall(EFFirewall newFirewall, NotificationChain msgs)
  {
    EFFirewall oldFirewall = firewall;
    firewall = newFirewall;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_HEADER__FIREWALL, oldFirewall, newFirewall);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirewall(EFFirewall newFirewall)
  {
    if (newFirewall != firewall)
    {
      NotificationChain msgs = null;
      if (firewall != null)
        msgs = ((InternalEObject)firewall).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_HEADER__FIREWALL, null, msgs);
      if (newFirewall != null)
        msgs = ((InternalEObject)newFirewall).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_HEADER__FIREWALL, null, msgs);
      msgs = basicSetFirewall(newFirewall, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_HEADER__FIREWALL, newFirewall, newFirewall));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_HEADER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EFImports> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<EFImports>(EFImports.class, this, EasyWallPackage.EF_HEADER__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_HEADER__RULES:
        return ((InternalEList<?>)getRules()).basicRemove(otherEnd, msgs);
      case EasyWallPackage.EF_HEADER__FIREWALL:
        return basicSetFirewall(null, msgs);
      case EasyWallPackage.EF_HEADER__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_HEADER__RULES:
        return getRules();
      case EasyWallPackage.EF_HEADER__FIREWALL:
        return getFirewall();
      case EasyWallPackage.EF_HEADER__NAME:
        return getName();
      case EasyWallPackage.EF_HEADER__IMPORTS:
        return getImports();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_HEADER__RULES:
        getRules().clear();
        getRules().addAll((Collection<? extends EFRule>)newValue);
        return;
      case EasyWallPackage.EF_HEADER__FIREWALL:
        setFirewall((EFFirewall)newValue);
        return;
      case EasyWallPackage.EF_HEADER__NAME:
        setName((String)newValue);
        return;
      case EasyWallPackage.EF_HEADER__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends EFImports>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_HEADER__RULES:
        getRules().clear();
        return;
      case EasyWallPackage.EF_HEADER__FIREWALL:
        setFirewall((EFFirewall)null);
        return;
      case EasyWallPackage.EF_HEADER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EasyWallPackage.EF_HEADER__IMPORTS:
        getImports().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_HEADER__RULES:
        return rules != null && !rules.isEmpty();
      case EasyWallPackage.EF_HEADER__FIREWALL:
        return firewall != null;
      case EasyWallPackage.EF_HEADER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EasyWallPackage.EF_HEADER__IMPORTS:
        return imports != null && !imports.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EFHeaderImpl
