/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.easywall.easyWall.EFMember;
import org.xtext.example.easywall.easyWall.EFNetworkNativeType;
import org.xtext.example.easywall.easyWall.EFPrimitiveType;
import org.xtext.example.easywall.easyWall.EFRuleClass;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Member</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFMemberImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFMemberImpl#getRuletype <em>Ruletype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFMemberImpl#getNativetype <em>Nativetype</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFMemberImpl#getPrimitivetype <em>Primitivetype</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFMemberImpl extends MinimalEObjectImpl.Container implements EFMember
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRuletype() <em>Ruletype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRuletype()
   * @generated
   * @ordered
   */
  protected EFRuleClass ruletype;

  /**
   * The default value of the '{@link #getNativetype() <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNativetype()
   * @generated
   * @ordered
   */
  protected static final EFNetworkNativeType NATIVETYPE_EDEFAULT = EFNetworkNativeType.NETWORK;

  /**
   * The cached value of the '{@link #getNativetype() <em>Nativetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNativetype()
   * @generated
   * @ordered
   */
  protected EFNetworkNativeType nativetype = NATIVETYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getPrimitivetype() <em>Primitivetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimitivetype()
   * @generated
   * @ordered
   */
  protected static final EFPrimitiveType PRIMITIVETYPE_EDEFAULT = EFPrimitiveType.INT;

  /**
   * The cached value of the '{@link #getPrimitivetype() <em>Primitivetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimitivetype()
   * @generated
   * @ordered
   */
  protected EFPrimitiveType primitivetype = PRIMITIVETYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFMemberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_MEMBER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_MEMBER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFRuleClass getRuletype()
  {
    if (ruletype != null && ruletype.eIsProxy())
    {
      InternalEObject oldRuletype = (InternalEObject)ruletype;
      ruletype = (EFRuleClass)eResolveProxy(oldRuletype);
      if (ruletype != oldRuletype)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EasyWallPackage.EF_MEMBER__RULETYPE, oldRuletype, ruletype));
      }
    }
    return ruletype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFRuleClass basicGetRuletype()
  {
    return ruletype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRuletype(EFRuleClass newRuletype)
  {
    EFRuleClass oldRuletype = ruletype;
    ruletype = newRuletype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_MEMBER__RULETYPE, oldRuletype, ruletype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetworkNativeType getNativetype()
  {
    return nativetype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNativetype(EFNetworkNativeType newNativetype)
  {
    EFNetworkNativeType oldNativetype = nativetype;
    nativetype = newNativetype == null ? NATIVETYPE_EDEFAULT : newNativetype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_MEMBER__NATIVETYPE, oldNativetype, nativetype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFPrimitiveType getPrimitivetype()
  {
    return primitivetype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrimitivetype(EFPrimitiveType newPrimitivetype)
  {
    EFPrimitiveType oldPrimitivetype = primitivetype;
    primitivetype = newPrimitivetype == null ? PRIMITIVETYPE_EDEFAULT : newPrimitivetype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_MEMBER__PRIMITIVETYPE, oldPrimitivetype, primitivetype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_MEMBER__NAME:
        return getName();
      case EasyWallPackage.EF_MEMBER__RULETYPE:
        if (resolve) return getRuletype();
        return basicGetRuletype();
      case EasyWallPackage.EF_MEMBER__NATIVETYPE:
        return getNativetype();
      case EasyWallPackage.EF_MEMBER__PRIMITIVETYPE:
        return getPrimitivetype();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_MEMBER__NAME:
        setName((String)newValue);
        return;
      case EasyWallPackage.EF_MEMBER__RULETYPE:
        setRuletype((EFRuleClass)newValue);
        return;
      case EasyWallPackage.EF_MEMBER__NATIVETYPE:
        setNativetype((EFNetworkNativeType)newValue);
        return;
      case EasyWallPackage.EF_MEMBER__PRIMITIVETYPE:
        setPrimitivetype((EFPrimitiveType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_MEMBER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EasyWallPackage.EF_MEMBER__RULETYPE:
        setRuletype((EFRuleClass)null);
        return;
      case EasyWallPackage.EF_MEMBER__NATIVETYPE:
        setNativetype(NATIVETYPE_EDEFAULT);
        return;
      case EasyWallPackage.EF_MEMBER__PRIMITIVETYPE:
        setPrimitivetype(PRIMITIVETYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_MEMBER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EasyWallPackage.EF_MEMBER__RULETYPE:
        return ruletype != null;
      case EasyWallPackage.EF_MEMBER__NATIVETYPE:
        return nativetype != NATIVETYPE_EDEFAULT;
      case EasyWallPackage.EF_MEMBER__PRIMITIVETYPE:
        return primitivetype != PRIMITIVETYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nativetype: ");
    result.append(nativetype);
    result.append(", primitivetype: ");
    result.append(primitivetype);
    result.append(')');
    return result.toString();
  }

} //EFMemberImpl
