/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.easyWall.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.easywall.easyWall.EFNetworkConstant;
import org.xtext.example.easywall.easyWall.EasyWallPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EF Network Constant</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFNetworkConstantImpl#getNetwork <em>Network</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFNetworkConstantImpl#getVarip <em>Varip</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFNetworkConstantImpl#getVarnetmask <em>Varnetmask</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFNetworkConstantImpl#getRawip <em>Rawip</em>}</li>
 *   <li>{@link org.xtext.example.easywall.easyWall.impl.EFNetworkConstantImpl#getRawnetmask <em>Rawnetmask</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFNetworkConstantImpl extends EFExpressionImpl implements EFNetworkConstant
{
  /**
   * The cached value of the '{@link #getNetwork() <em>Network</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNetwork()
   * @generated
   * @ordered
   */
  protected EFNetworkConstant network;

  /**
   * The default value of the '{@link #getVarip() <em>Varip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarip()
   * @generated
   * @ordered
   */
  protected static final String VARIP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarip() <em>Varip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarip()
   * @generated
   * @ordered
   */
  protected String varip = VARIP_EDEFAULT;

  /**
   * The default value of the '{@link #getVarnetmask() <em>Varnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarnetmask()
   * @generated
   * @ordered
   */
  protected static final String VARNETMASK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarnetmask() <em>Varnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarnetmask()
   * @generated
   * @ordered
   */
  protected String varnetmask = VARNETMASK_EDEFAULT;

  /**
   * The default value of the '{@link #getRawip() <em>Rawip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawip()
   * @generated
   * @ordered
   */
  protected static final String RAWIP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRawip() <em>Rawip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawip()
   * @generated
   * @ordered
   */
  protected String rawip = RAWIP_EDEFAULT;

  /**
   * The default value of the '{@link #getRawnetmask() <em>Rawnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawnetmask()
   * @generated
   * @ordered
   */
  protected static final int RAWNETMASK_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRawnetmask() <em>Rawnetmask</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRawnetmask()
   * @generated
   * @ordered
   */
  protected int rawnetmask = RAWNETMASK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFNetworkConstantImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasyWallPackage.Literals.EF_NETWORK_CONSTANT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EFNetworkConstant getNetwork()
  {
    return network;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNetwork(EFNetworkConstant newNetwork, NotificationChain msgs)
  {
    EFNetworkConstant oldNetwork = network;
    network = newNetwork;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK, oldNetwork, newNetwork);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNetwork(EFNetworkConstant newNetwork)
  {
    if (newNetwork != network)
    {
      NotificationChain msgs = null;
      if (network != null)
        msgs = ((InternalEObject)network).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK, null, msgs);
      if (newNetwork != null)
        msgs = ((InternalEObject)newNetwork).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK, null, msgs);
      msgs = basicSetNetwork(newNetwork, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK, newNetwork, newNetwork));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarip()
  {
    return varip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarip(String newVarip)
  {
    String oldVarip = varip;
    varip = newVarip;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__VARIP, oldVarip, varip));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarnetmask()
  {
    return varnetmask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarnetmask(String newVarnetmask)
  {
    String oldVarnetmask = varnetmask;
    varnetmask = newVarnetmask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__VARNETMASK, oldVarnetmask, varnetmask));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRawip()
  {
    return rawip;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRawip(String newRawip)
  {
    String oldRawip = rawip;
    rawip = newRawip;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__RAWIP, oldRawip, rawip));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRawnetmask()
  {
    return rawnetmask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRawnetmask(int newRawnetmask)
  {
    int oldRawnetmask = rawnetmask;
    rawnetmask = newRawnetmask;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EasyWallPackage.EF_NETWORK_CONSTANT__RAWNETMASK, oldRawnetmask, rawnetmask));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK:
        return basicSetNetwork(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK:
        return getNetwork();
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARIP:
        return getVarip();
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARNETMASK:
        return getVarnetmask();
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWIP:
        return getRawip();
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWNETMASK:
        return getRawnetmask();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK:
        setNetwork((EFNetworkConstant)newValue);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARIP:
        setVarip((String)newValue);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARNETMASK:
        setVarnetmask((String)newValue);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWIP:
        setRawip((String)newValue);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWNETMASK:
        setRawnetmask((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK:
        setNetwork((EFNetworkConstant)null);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARIP:
        setVarip(VARIP_EDEFAULT);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARNETMASK:
        setVarnetmask(VARNETMASK_EDEFAULT);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWIP:
        setRawip(RAWIP_EDEFAULT);
        return;
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWNETMASK:
        setRawnetmask(RAWNETMASK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EasyWallPackage.EF_NETWORK_CONSTANT__NETWORK:
        return network != null;
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARIP:
        return VARIP_EDEFAULT == null ? varip != null : !VARIP_EDEFAULT.equals(varip);
      case EasyWallPackage.EF_NETWORK_CONSTANT__VARNETMASK:
        return VARNETMASK_EDEFAULT == null ? varnetmask != null : !VARNETMASK_EDEFAULT.equals(varnetmask);
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWIP:
        return RAWIP_EDEFAULT == null ? rawip != null : !RAWIP_EDEFAULT.equals(rawip);
      case EasyWallPackage.EF_NETWORK_CONSTANT__RAWNETMASK:
        return rawnetmask != RAWNETMASK_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (varip: ");
    result.append(varip);
    result.append(", varnetmask: ");
    result.append(varnetmask);
    result.append(", rawip: ");
    result.append(rawip);
    result.append(", rawnetmask: ");
    result.append(rawnetmask);
    result.append(')');
    return result.toString();
  }

} //EFNetworkConstantImpl
