/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.easywall.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.easywall.parser.antlr.internal.InternalEasyWallParser;
import org.xtext.example.easywall.services.EasyWallGrammarAccess;

public class EasyWallParser extends AbstractAntlrParser {

	@Inject
	private EasyWallGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEasyWallParser createParser(XtextTokenStream stream) {
		return new InternalEasyWallParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EFProgram";
	}

	public EasyWallGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EasyWallGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
