/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.easywall.scoping;

import com.google.common.base.Function;
import com.google.common.collect.Iterables;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.xtext.example.easywall.easyWall.EFBlock;
import org.xtext.example.easywall.easyWall.EFField;
import org.xtext.example.easywall.easyWall.EFHeader;
import org.xtext.example.easywall.easyWall.EFImports;
import org.xtext.example.easywall.easyWall.EFMethod;
import org.xtext.example.easywall.easyWall.EFParameter;
import org.xtext.example.easywall.easyWall.EFProgram;
import org.xtext.example.easywall.easyWall.EFRule;
import org.xtext.example.easywall.easyWall.EFRuleClass;
import org.xtext.example.easywall.easyWall.EFRuleReference;
import org.xtext.example.easywall.easyWall.EFStatement;
import org.xtext.example.easywall.easyWall.EFSymbolRef;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EasyWallScopeProvider extends AbstractEasyWallScopeProvider {
  public IScope scope_EFRuleReference_rule(final EFRuleReference ref) {
    return this.scopeForRules(ref);
  }

  private IScope scopeForRules(final EObject ctx) {
    final Resource resource = ctx.eResource();
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final EFProgram root = ((EFProgram) _head);
    final EFHeader header = root.getHeader();
    final Function1<Resource, EObject> _function = (Resource it) -> {
      return IterableExtensions.<EObject>head(it.getContents());
    };
    final Function1<EFProgram, List<EFRuleClass>> _function_1 = (EFProgram it) -> {
      final Function1<EFRule, EFRuleClass> _function_2 = (EFRule r) -> {
        return r.getRules();
      };
      return ListExtensions.<EFRule, EFRuleClass>map(it.getRules(), _function_2);
    };
    final Iterable<EFRuleClass> allRules = Iterables.<EFRuleClass>concat(IterableExtensions.<EFProgram, List<EFRuleClass>>map(Iterables.<EFProgram>filter(ListExtensions.<Resource, EObject>map(resource.getResourceSet().getResources(), _function), EFProgram.class), _function_1));
    String _elvis = null;
    String _name = null;
    if (header!=null) {
      _name=header.getName();
    }
    String _string = null;
    if (_name!=null) {
      _string=_name.toString();
    }
    if (_string != null) {
      _elvis = _string;
    } else {
      _elvis = "";
    }
    final String currentPackage = _elvis;
    final Function1<EFRuleClass, Boolean> _function_2 = (EFRuleClass it) -> {
      boolean _and = false;
      EObject _eContainer = it.eContainer();
      if (!(_eContainer instanceof EFProgram)) {
        _and = false;
      } else {
        EObject _eContainer_1 = it.eContainer();
        EFHeader _header = ((EFProgram) _eContainer_1).getHeader();
        String _name_1 = null;
        if (_header!=null) {
          _name_1=_header.getName();
        }
        String _string_1 = null;
        if (_name_1!=null) {
          _string_1=_name_1.toString();
        }
        boolean _equals = Objects.equals(_string_1, currentPackage);
        _and = _equals;
      }
      return Boolean.valueOf(_and);
    };
    final Iterable<EFRuleClass> localRules = IterableExtensions.<EFRuleClass>filter(allRules, _function_2);
    final ArrayList<EFRuleClass> importedRules = CollectionLiterals.<EFRuleClass>newArrayList();
    EList<EFImports> _imports = header.getImports();
    for (final EFImports imp : _imports) {
      {
        final String ns = imp.getImportedNamespace().toString();
        boolean _endsWith = ns.endsWith(".*");
        if (_endsWith) {
          int _length = ns.length();
          int _minus = (_length - 2);
          final String pkg = ns.substring(0, _minus);
          final Function1<EFRuleClass, Boolean> _function_3 = (EFRuleClass it) -> {
            EObject _eContainer = it.eContainer();
            EFHeader _header = ((EFProgram) _eContainer).getHeader();
            String _name_1 = null;
            if (_header!=null) {
              _name_1=_header.getName();
            }
            String _string_1 = null;
            if (_name_1!=null) {
              _string_1=_name_1.toString();
            }
            return Boolean.valueOf(Objects.equals(_string_1, pkg));
          };
          Iterable<EFRuleClass> _filter = IterableExtensions.<EFRuleClass>filter(allRules, _function_3);
          Iterables.<EFRuleClass>addAll(importedRules, _filter);
        } else {
          final Function1<EFRuleClass, Boolean> _function_4 = (EFRuleClass it) -> {
            EObject _eContainer = it.eContainer();
            EFHeader _header = ((EFProgram) _eContainer).getHeader();
            String _name_1 = null;
            if (_header!=null) {
              _name_1=_header.getName();
            }
            String _string_1 = null;
            if (_name_1!=null) {
              _string_1=_name_1.toString();
            }
            String _plus = (_string_1 + ".");
            String _name_2 = it.getName();
            String _plus_1 = (_plus + _name_2);
            return Boolean.valueOf(Objects.equals(_plus_1, ns));
          };
          Iterable<EFRuleClass> _filter_1 = IterableExtensions.<EFRuleClass>filter(allRules, _function_4);
          Iterables.<EFRuleClass>addAll(importedRules, _filter_1);
        }
      }
    }
    Iterable<EFRuleClass> _plus = Iterables.<EFRuleClass>concat(localRules, importedRules);
    Iterable<EFRuleClass> _plus_1 = Iterables.<EFRuleClass>concat(_plus, allRules);
    final Function<EFRuleClass, QualifiedName> _function_3 = (EFRuleClass r) -> {
      return QualifiedName.create(r.getName());
    };
    return Scopes.<EFRuleClass>scopeFor(_plus_1, _function_3, IScope.NULLSCOPE);
  }

  public IScope scope_EFSymbolRef_symbol(final EFSymbolRef ctx, final EReference ref) {
    IScope scope = IScope.NULLSCOPE;
    scope = this.scopeBlock(ctx, scope);
    scope = this.scopeMethod(ctx, scope);
    scope = this.scopeRule(ctx, scope);
    scope = this.scopeFirewall(ctx, scope);
    return scope;
  }

  public IScope scopeBlock(final EObject ctx, final IScope parent) {
    final EFBlock block = EcoreUtil2.<EFBlock>getContainerOfType(ctx, EFBlock.class);
    if ((block == null)) {
      return parent;
    }
    final Function<EFField, QualifiedName> _function = (EFField it) -> {
      return QualifiedName.create(it.getName());
    };
    return Scopes.<EFField>scopeFor(
      Iterables.<EFField>filter(block.getStatements(), EFField.class), _function, parent);
  }

  public IScope scopeMethod(final EObject ctx, final IScope parent) {
    final EFMethod method = EcoreUtil2.<EFMethod>getContainerOfType(ctx, EFMethod.class);
    if ((method == null)) {
      return parent;
    }
    final EList<EFParameter> params = method.getParams();
    Iterable<EFField> _elvis = null;
    EFBlock _body = method.getBody();
    EList<EFStatement> _statements = null;
    if (_body!=null) {
      _statements=_body.getStatements();
    }
    Iterable<EFField> _filter = null;
    if (_statements!=null) {
      _filter=Iterables.<EFField>filter(_statements, EFField.class);
    }
    if (_filter != null) {
      _elvis = _filter;
    } else {
      List<EFField> _emptyList = CollectionLiterals.<EFField>emptyList();
      _elvis = _emptyList;
    }
    final Iterable<EFField> locals = _elvis;
    Iterable<EObject> _plus = Iterables.<EObject>concat(params, locals);
    final Function<EObject, QualifiedName> _function = (EObject it) -> {
      return this.getQName(it);
    };
    return Scopes.<EObject>scopeFor(_plus, _function, parent);
  }

  public QualifiedName getQName(final EObject obj) {
    QualifiedName _switchResult = null;
    boolean _matched = false;
    if (obj instanceof EFField) {
      _matched=true;
      _switchResult = QualifiedName.create(((EFField)obj).getName());
    }
    if (!_matched) {
      if (obj instanceof EFParameter) {
        _matched=true;
        _switchResult = QualifiedName.create(((EFParameter)obj).getName());
      }
    }
    if (!_matched) {
      _switchResult = QualifiedName.create("unknown");
    }
    return _switchResult;
  }

  public IScope scopeRule(final EObject ctx, final IScope parent) {
    final EFRuleClass rule = EcoreUtil2.<EFRuleClass>getContainerOfType(ctx, EFRuleClass.class);
    if ((rule == null)) {
      return parent;
    }
    final Function<EFField, QualifiedName> _function = (EFField it) -> {
      return QualifiedName.create(it.getName());
    };
    return Scopes.<EFField>scopeFor(
      Iterables.<EFField>filter(rule.getMembers(), EFField.class), _function, parent);
  }

  public IScope scopeFirewall(final EObject ctx, final IScope parent) {
    final EFProgram program = EcoreUtil2.<EFProgram>getContainerOfType(ctx, EFProgram.class);
    if (((program == null) || (program.getFirewall() == null))) {
      return parent;
    }
    final Function<EFField, QualifiedName> _function = (EFField it) -> {
      return QualifiedName.create(it.getName());
    };
    return Scopes.<EFField>scopeFor(
      Iterables.<EFField>filter(program.getFirewall().getMembers(), EFField.class), _function, parent);
  }
}
